set system parameters 'insert_execution_mode=1';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=2';
drop table IF EXISTS coo; 
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;

set system parameters 'insert_execution_mode=3';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=5';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=10';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=18';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=7';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=11';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=19';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=14';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=22';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=26';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=15';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=23';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=27';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=30';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=31';
create table coo(col1 int auto_increment primary key, col2 int);
insert into coo(col2) values(33);
insert into coo(col2) values(44);
insert into coo(col2) values(55);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
create table coo(col1 int , col2 int);
insert into coo select rownum,rownum+1 from  db_class a,db_class b limit 100;
insert into coo values(3,4);
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
create table coo(col1 int unique , col2 int);
insert into coo select rownum,rownum+1 from  db_class a,db_class b limit 100;
replace into coo values(3,4);
insert into coo values(7,8) on duplicate key  update col1=7;
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
create table coo(col1 int unique , col2 int);
replace into coo values(3,4);
insert into coo values(3,8) on duplicate key update  col1=3;
alter table coo change col1 aaa int auto_increment; 
insert into coo(col2) values(66);
drop coo;
set system parameters 'insert_execution_mode=3';
