drop table if exists aa;
drop table if exists bb;
drop table if exists cc;
create table aa(a int primary key, b int);
create table bb(a int primary key, b int);
create table cc(a int primary key, b int);
insert into aa values(1,1);
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into aa select a+(select count(*) from aa), 1 from aa;
insert into bb select * from aa;
insert into cc select a, 1 from aa where a <= 5;
update statistics on all classes;
select bb.* from aa inner join bb on bb.a = aa.a inner join cc on cc.a = aa.a and cc.b=1 where bb.a in (1,2) order by bb.b,bb.a;
select bb.* from aa inner join bb on bb.a = aa.a and bb.a in (1,2) inner join cc on cc.a = aa.a and cc.b=1 order by bb.b,bb.a;
drop table if exists aa;
drop table if exists bb;
drop table if exists cc;
