drop table if exists t1;
create table t1(a int);
alter table t1 modify a int not null primary key;
alter table t1 modify a int not null;
alter table t1 modify a int primary key;
drop table if exists t1;
create table t1(a int);
alter table t1 modify a  int not null;
alter table t1 modify a  int not null primary key;
alter table t1 modify a  int primary key;
drop table if exists t1;
create table t1(a int);
alter table t1 change a a1 int not null primary key;
alter table t1 change a1 a2 int not null;
alter table t1 change a2 a3 int primary key;
drop table if exists t1;
create table t1(a int);
alter table t1 change a a1 int not null;
alter table t1 change a1 a2 int not null primary key;
alter table t1 change a2 a3 int primary key;
drop table if exists t1;
