drop table if exists tb;
create table tb(i numeric(6,2));
insert into tb values(0);
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb values(0);
insert into tb values(0);
insert into tb values(0);
insert into tb values(2440.00);
select sum(i),count(i),sum(i)/count(i) from tb;
drop tb;

create table tb(i numeric(6,2));
insert into tb values(0);
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb select i from tb;
insert into tb values(0);
insert into tb values(0);
insert into tb values(0);
insert into tb values(-2440.00);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast(-2440.00/36 as numeric(6,2));
drop tb;

drop if exists tb;
create table tb(i numeric(6,2));
insert into tb values(22.25),(30.44),(28.4),(30);
insert into tb values(0);
select sum(i),count(*),sum(i)/count(*) from tb;
drop tb;

create table tb(i numeric(6,2),j numeric(6,2) ,k numeric(6,2),l numeric(6,2));
insert into tb values(22.25,30.44,28.4,30);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
select sum(i)+sum(j)+sum(k)+sum(l),count(*),(sum(i)+sum(j)+sum(k)+sum(l))/count(*) from tb;
drop tb;

create table tb(i numeric(6,2),j numeric(6,2) ,k numeric(6,2),l numeric(6,2));
insert into tb values(-22.25,-30.44,-28.4,-30);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
insert into tb values(0,0,0,0);
select sum(i)+sum(j)+sum(k)+sum(l),count(*),(sum(i)+sum(j)+sum(k)+sum(l))/count(*) from tb;
select cast(-111.09/5 as numeric(6,2));
drop tb;

create table tb(i numeric(5,3));
insert into tb values(5);
select sum(i),sum(i)/3,sum(i)/6 from tb;
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
select sum(i),count(i),sum(i)/count(i) from tb;
delete from tb where i=0;
insert into tb values(-6),(-6),(-10);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-6);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-16);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-5);
select sum(i),count(i),sum(i)/count(i) from tb;
drop tb;

create table tb(i double);
insert into tb values(5);
select sum(i),sum(i)/3,sum(i)/6 from tb;
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
select sum(i),count(i),sum(i)/count(i) from tb;
delete from tb where i=0;
insert into tb values(-6),(-6),(-10);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-6);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-16);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-5);
select sum(i),count(i),sum(i)/count(i) from tb;
drop tb;
create table tb(i float);
insert into tb values(5);
select sum(i),sum(i)/3,sum(i)/6 from tb;
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(6);
select sum(i),count(i),sum(i)/count(i) from tb;
delete from tb where i=0;
insert into tb values(-6),(-6),(-10);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-6);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-16);
select sum(i),count(i),sum(i)/count(i) from tb;
insert into tb values(-5);
select sum(i),count(i),sum(i)/count(i) from tb;
drop tb;

create table tb(i numeric(18,13));
insert into tb values(5);
select sum(i),sum(i)/3,sum(i)/6 from tb;
select cast (sum(i)/ 6 as numeric(18,13)) from tb;
select cast (sum(i)/6 as numeric(18,2)) from tb;
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
insert into tb values(6);
insert into tb values(0),(0);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
insert into tb values(6);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
delete from tb where i=0;
insert into tb values(-6),(-6),(-10);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
insert into tb values(-6);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
insert into tb values(-16);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
insert into tb values(-5);
select sum(i),count(i),sum(i)/count(i) from tb;
select cast (sum(i)/count(i) as numeric(18,13)) from tb;
select cast (sum(i)/count(i) as numeric(18,2)) from tb;
drop tb;



