autocommit off;
create class a (f a);
create class b as subclass of a;
alter class b add attribute f b;
insert into b default values to :b;
insert into a values (:b);
select f from all a;
drop class a;
drop class b;
create class a (f a);
create class b (f b);
alter class b add superclass a;
insert into b default values to :b;
insert into a values (:b);
select f from all a;
drop class a;
drop class b;
create class a (f a);
create class b as subclass of a (f b);
insert into b default values to :b;
insert into a values (:b);
select f from all a;
drop class a;
drop class b;
rollback;
