autocommit off;
create class cc 
class attribute(ca int default 10)
(a int, b int shared 123, class cb int default 20);
insert into cc values( 99, 123 );
select class cc.ca, b from cc;
select ca, cb from class cc;
update class cc set ca = 70, cb = 77 where ca = 10 and cb = 20;
select ca, cb from class cc;
select * from cc;
select class cc.ca, u from db_user u;
rollback work;
create class X (class a int default 25);
create class Y as subclass of X (b int);
insert into X default values;
insert into Y(b) values(42);
select class X.a from X;	
select a from class X;		
select class Y.a from Y;	
select a from class Y;		
update class X set a = 13;
select class X.a from X;	
select a from class X;		
select class Y.a from Y;	
select a from class Y;		
update class Y set a = 42;
select class X.a from X;	
select a from class X;		
select class Y.a from Y;	
select a from class Y;		
rollback work;
create class X (a int shared 25);
create class Y as subclass of X (b int);
create class Z as subclass of Y (a int);
insert into X default values;
insert into Y(b) values(42);
insert into Z(a) values(69);
select a from all X;	
select a from all Y;	
select a from all Z;	
select a from (Y, Z);	
select a from (Z, Y);	
update Y set a = 101;
select a from all X;	
select a from all Y;	
select a from all Z;	
select a from (Y, Z);	
select a from (Z, Y);	
rollback work;
create class x (a int shared NULL);
insert into x values (10);	
insert into x values (20);
select * from x;
rollback;
