autocommit off;
create class y (c string);
insert into y values ('hi') to :y1;
insert into y values ('del') to :y2;
create class ys as subclass of y;
insert into ys values ('there') to :ys1;
insert into ys values ('ete') to :ys2;
create class x( a int, b y);
insert into x values (1, :y1);
insert into x values (2, NULL);
insert into x values (3, :ys1);
insert into x values (4, :y2);
insert into x values (5, :ys2);
select x.a, x.b.c from x  order by 1;
select x.a, x.b{y}.c from x,y order by 1;
delete from y where y = :y2 ;
delete from ys where ys = :ys2 ;
select x.a, x.b.c from x order by 1;	
select x.a, x.b{y}.c from x,y order by 1;
rollback;
