autocommit off;
call login('joe') on class db_user;
create class joe.xxx (a int);
insert into joe.xxx values(6);
create vclass joe.xxx_v (a1 int) as select a from joe.xxx;
select * from xxx_v;
grant all on xxx_v to public;
call login('public') on class db_user;
select * from joe.xxx_v;
insert into joe.xxx_v values(12);
select * from joe.xxx_v;
delete from joe.xxx_v where a1=6;
select * from joe.xxx_v;
update joe.xxx_v set a1=9 where a1=12;
select * from joe.xxx_v;
call login('dba', '') on class db_user;
rollback;
