autocommit off;
select unique(off_season) from public.bed_and_breakfast;
select unique(off_season) from public.resort;
select unique(off_season) from public.motel;
select unique(off_season) from public.hotel;
select unique(off_season) from public.accommodations;
select unique(state) from joe.nu_fac_v;
select unique(state) from joe.u_fac_v;
select unique(attr_2) from joe.kitsch_v;
select unique(attr_5) from joe.kitsch_v;
select unique(attr_6) from joe.kitsch_v;
select unique(set_attr_2) from joe.kitsch_v;
select unique(set_attr_5) from joe.kitsch_v;
select unique(set_attr_6) from joe.kitsch_v;
select unique(cattr_2) from joe.kitsch_c;
select unique(cattr_5) from joe.kitsch_c;
select unique(cattr_6) from joe.kitsch_c;
select unique(cset_attr_2) from joe.kitsch_c;
select unique(cset_attr_5) from joe.kitsch_c;
select unique(cset_attr_6) from joe.kitsch_c;
rollback;
