autocommit off;
select unique(off_season) from bed_and_breakfast;
select unique(off_season) from resort;
select unique(off_season) from motel;
select unique(off_season) from hotel;
select unique(off_season) from accommodations;
select unique(state) from nu_fac_v;
select unique(state) from u_fac_v;
select unique(attr_2) from kitsch_v;
select unique(attr_5) from kitsch_v;
select unique(attr_6) from kitsch_v;
select unique(set_attr_2) from kitsch_v;
select unique(set_attr_5) from kitsch_v;
select unique(set_attr_6) from kitsch_v;
select unique(cattr_2) from kitsch_c;
select unique(cattr_5) from kitsch_c;
select unique(cattr_6) from kitsch_c;
select unique(cset_attr_2) from kitsch_c;
select unique(cset_attr_5) from kitsch_c;
select unique(cset_attr_6) from kitsch_c;
rollback;
