autocommit off;
create class a (a_i int);
insert into a values (1);
insert into a values (2);
create class a_sub under a ( c_i int);
insert into a_sub (a_i,c_i) values (3,210);
select * from a order by a_i;
select * from a_sub;
select * from all a order by a_i;
create vclass v (a) as select a_i from all a;
select * from v order by a;
select count(*) from v;
select * from all v order by a;
select count(*) from all v;
rollback;
