autocommit off;
create class a (a_i int, b_i int);
create class b (a_i int, b_i int);
insert into a values(1,1);
insert into a values(1,2);
insert into b values(1,1);
insert into b values(1,2);
create vclass v1(a int,b int) as select a_i,b_i from a union select a_i,b_i from b; 
create vclass v2(a int,b int) as select a_i,b_i from a union all select a_i,b_i from b; 
select a from v1;
select distinct a from v1;
select count(a),count(distinct a),count(b),count(distinct b) from v1;
select a from v2;
select distinct a from v2;
select count(a),count(distinct a),count(b),count(distinct b) from v2;
rollback;
