autocommit off;
set names utf8;
create table a ( c char(1)) charset euckr;
insert into a values('e');
select c,'a',set{c,'a'} from a;
select c,'a',set{c,'e'} from a;
select c,'w',set{c,'w'} from a;
create table e ( c char(2)) charset euckr;
insert into e values('하');
select c,'가',set{c,'가'} from e;
select c,'하',set{c,'하'} from e;
select c,'허',set{c,'허'} from e;
create table f ( c bit(8)) charset euckr;
insert into f values(B'00000010');
select c,'00000001',set{c,B'00000001'} from f;
select c,'00000010',set{c,B'00000010'} from f;
select c,'00000011',set{c,B'00000011'} from f;
create table b ( c char(1),v varchar(1)) charset euckr;
insert into b values('e','a');
select v,c,set{v,c} from b;
create table c (c char(2),v char varying(2)) charset euckr;
insert into c values('하','허');
select v,c,set{v,c} from c;
create table d ( c bit(8),v bit varying(8)) charset euckr;
insert into d values(B'00000001',B'00000000');
select v,c,set{v,c} from d;
set names iso88591;
rollback;
