autocommit off;
create class a0 (n int, s string);
create class a1 as subclass of a0;
insert into a1 values (0, 'abcdefghijklmnopqrstuvwxyz');
insert into a1 values (1, 'abcdefghijklmnopqrstuvwxyz');
insert into a1 values (2, 'abcdefghijklmnopqrstuvwxyz');
insert into a1 values (3, 'abcdefghijklmnopqrstuvwxyz');
insert into a1 select n+4, s from a1;
insert into a1 select n+8, s from a1;
insert into a1 select n+16, s from a1;
insert into a1 select n+32, s from a1;
insert into a1 select n+64, s from a1;
insert into a1 select n+128, s from a1;
create index i_a0_n on a0(n);
create index i_a1_n on a1(n);
--set optimization: level 257;
select count(*) from all a1 where n = 15;
select count(*) from all a0 where n = 15;
insert into a0 values (1000, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ');
delete from a0;
select count(*) from all a0 where n = 15;
update statistics on a0;
select count(*) from all a0 where n = 15;
rollback work;
rollback;
