autocommit off;
create class foo (a int, b float);
insert into foo values (1, 2.2);
alter foo add attribute c double;
update foo set c = 3.3;
select * from foo;
rollback work;
create class foo (a double, b float);
insert into foo values (1, 2.2);
alter foo add attribute c double;
update foo set c = 3.3;
select * from foo;
rollback work;
create class foo (a int, b short);
insert into foo values (1, 2);
alter foo add attribute c int;
update foo set c = 3;
select * from foo;
rollback work;
create class foo (a int, b float);
create trigger foo_trigger before update on foo execute print 'testing';
insert into foo values (1, 2.2);
alter foo add attribute c double;
update foo set c = 3.3;
select * from foo;
rollback work;
create class foo (a double, b float);
create trigger foo_trigger before update on foo execute print 'testing';
insert into foo values (1, 2.2);
alter foo add attribute c double;
update foo set c = 3.3;
select * from foo;
rollback work;
create class foo (a int, b short);
create trigger foo_trigger before update on foo execute print 'testing';
insert into foo values (1, 2);
alter foo add attribute c int;
update foo set c = 3;
select * from foo;
rollback work;
rollback;
