autocommit off;
select multiset{1, 2, 3, 4} to :lhs from db_root;
select  multiset{1, 2, 3, 4} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{1, 2, 3, 4} to :lhs from db_root;
select multiset{2, 4, 6, 8} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{1, 2, 3, 4} to :lhs from db_root;
select multiset{3, 4, 5, 6} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{1, 1, 2, 2, 3, 3, 4, 4} to :lhs from db_root;
select multiset{1, 2, 3, 4} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{2, 2, 4, 4, 6, 6, 8, 8} to :lhs from db_root;
select multiset{1, 3, 5, 7} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{1, 3, 5, 7} to :lhs from db_root;
select multiset{2, 2, 4, 4, 6, 6, 8, 8} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
select multiset{0, 1, 2, 2, 3, 3, 4, 5} to :lhs from db_root;
select multiset{2, 3, 4, 5} to :rhs from db_root;
(select k from table(:lhs) t(k)) union      all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) union      distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) difference distinct (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  all      (select k from table(:rhs) t(k));
(select k from table(:lhs) t(k)) intersect  distinct (select k from table(:rhs) t(k));
rollback;
