autocommit off;
create class foo1 (a int);
create class foo2 under foo1 (b int);
insert into foo2 (a, b) values (1, 1);
select a, b from foo2 order by a, b;
alter class foo2 add attribute a int;
select a, b from foo2 order by a, b;
insert into foo2 (a, b) values (2, 2);
alter class foo2 drop attribute a;
select a, b from foo2 order by a, b;
rollback;
