autocommit off;
create class eeeoo (a int, b int, unique(a,b));
alter class eeeoo rename a as c;
select * from db_class where  class_name = 'eeeoo';
rollback;
create class eeeoo (a int, b int, unique(a,b));
alter class eeeoo drop a;
select * from db_class where class_name = 'eeeoo';
rollback;
create class eeeoo (a int, b int, unique(a,b));
create class subeeeoo under eeeoo (c int);
alter class eeeoo rename a as c;
select * from db_class where  class_name = 'subeeeoo';
rollback;
create class eeeoo (a int, b int, unique(a,b));
create class supereeeoo (b int);
alter class eeeoo add superclass supereeeoo;
select * from db_class where  class_name = 'supereeeoo';
alter class eeeoo drop attribute b;
select * from db_attribute where  class_name = 'eeeoo';
rollback;
create class eeeoo (a int);
create class subeeeoo under eeeoo (a int, b int, c int, unique(a,b));
alter class subeeeoo rename a as d;
select * from db_class where  class_name = 'subeeeoo';
rollback;
create class eeeoo1 (a int, b int, c int, unique(a,b));
create class eeeoo2 (a int, b int, d int, unique(b,d));
create class subeeeoo under eeeoo1, eeeoo2 inherit a of eeeoo1, b of eeeoo2;
select * from db_class where  class_name like '%eeeoo%';

rollback;
