autocommit off;
call login('dba','') on class db_user;
create class foo ( a int );
insert into foo values ( 1 );
insert into foo values ( 2 );
insert into foo select a from foo;
insert into foo select a from foo;
insert into foo select a from foo;
insert into foo select a from foo;
insert into foo select a from foo;
insert into foo select a from foo;
create index i_foo_a on foo ( a );
select set(select a from foo) into v from db_root;
commit;
--set optimization: level 257;
select a from foo where a in v order by 1 desc;
drop class foo;
call login('public','') on class db_user;
call login('dba','') on class db_user;
commit;
rollback;
