autocommit off;
create table test_add_months(
	c1 date,
	i2 integer,
	c3 date,
	i4 integer,
	add_months_1_1 date,
	add_months_1_2 date
);
insert into test_add_months(c1,i2,add_months_1_1,add_months_1_2) values(date '1/31/1999',100,date '1/31/1999',date '1/01/1999');
		select add_months(date '1/31/1999',1) from test_add_months;
		select add_months(date '1/31/1999',2) from test_add_months;
		select add_months(date '1/31/1999',3) from test_add_months;
		select add_months(date '1/31/1999',4) from test_add_months;
		select add_months(date '1/31/1999',5) from test_add_months;
		select add_months(date '1/31/1999',6) from test_add_months;
		select add_months(date '1/31/1999',7) from test_add_months;
		select add_months(date '1/31/1999',8) from test_add_months;
		select add_months(date '1/31/1999',9) from test_add_months;
		select add_months(date '1/31/1999',10) from test_add_months;
		select add_months(date '1/31/1999',11) from test_add_months;
		select add_months(date '1/31/1999',12) from test_add_months;
		select add_months(add_months_1_1,1) from test_add_months;
		select add_months(add_months_1_1,2) from test_add_months;
		select add_months(add_months_1_1,3) from test_add_months;
		select add_months(add_months_1_1,4) from test_add_months;
		select add_months(add_months_1_1,5) from test_add_months;
		select add_months(add_months_1_1,6) from test_add_months;
		select add_months(add_months_1_1,7) from test_add_months;
		select add_months(add_months_1_1,8) from test_add_months;
		select add_months(add_months_1_1,9) from test_add_months;
		select add_months(add_months_1_1,10) from test_add_months;
		select add_months(add_months_1_1,11) from test_add_months;
		select add_months(add_months_1_1,12) from test_add_months;
		select add_months(date '1/01/1999',1) from test_add_months;
		select add_months(date '1/01/1999',2) from test_add_months;
		select add_months(date '1/01/1999',3) from test_add_months;
		select add_months(date '1/01/1999',4) from test_add_months;
		select add_months(date '1/01/1999',5) from test_add_months;
		select add_months(date '1/01/1999',6) from test_add_months;
		select add_months(date '1/01/1999',7) from test_add_months;
		select add_months(date '1/01/1999',8) from test_add_months;
		select add_months(date '1/01/1999',9) from test_add_months;
		select add_months(date '1/01/1999',10) from test_add_months;
		select add_months(date '1/01/1999',11) from test_add_months;
		select add_months(date '1/01/1999',12) from test_add_months;
		select add_months(add_months_1_2,1) from test_add_months;
		select add_months(add_months_1_2,2) from test_add_months;
		select add_months(add_months_1_2,3) from test_add_months;
		select add_months(add_months_1_2,4) from test_add_months;
		select add_months(add_months_1_2,5) from test_add_months;
		select add_months(add_months_1_2,6) from test_add_months;
		select add_months(add_months_1_2,7) from test_add_months;
		select add_months(add_months_1_2,8) from test_add_months;
		select add_months(add_months_1_2,9) from test_add_months;
		select add_months(add_months_1_2,10) from test_add_months;
		select add_months(add_months_1_2,11) from test_add_months;
		select add_months(add_months_1_2,12) from test_add_months;
		select add_months(date '1/31/1999',-1) from test_add_months;
		select add_months(date '1/31/1999',-2) from test_add_months;
		select add_months(date '1/31/1999',-3) from test_add_months;
		select add_months(date '1/31/1999',-4) from test_add_months;
		select add_months(date '1/31/1999',-5) from test_add_months;
		select add_months(date '1/31/1999',-6) from test_add_months;
		select add_months(date '1/31/1999',-7) from test_add_months;
		select add_months(date '1/31/1999',-8) from test_add_months;
		select add_months(date '1/31/1999',-9) from test_add_months;
		select add_months(date '1/31/1999',-10) from test_add_months;
		select add_months(date '1/31/1999',-11) from test_add_months;
		select add_months(date '1/31/1999',-12) from test_add_months;
		select add_months(add_months_1_1,-1) from test_add_months;
		select add_months(add_months_1_1,-2) from test_add_months;
		select add_months(add_months_1_1,-3) from test_add_months;
		select add_months(add_months_1_1,-4) from test_add_months;
		select add_months(add_months_1_1,-5) from test_add_months;
		select add_months(add_months_1_1,-6) from test_add_months;
		select add_months(add_months_1_1,-7) from test_add_months;
		select add_months(add_months_1_1,-8) from test_add_months;
		select add_months(add_months_1_1,-9) from test_add_months;
		select add_months(add_months_1_1,-10) from test_add_months;
		select add_months(add_months_1_1,-11) from test_add_months;
		select add_months(add_months_1_1,-12) from test_add_months;
		select add_months(date '1/01/1999',-1) from test_add_months;
		select add_months(date '1/01/1999',-2) from test_add_months;
		select add_months(date '1/01/1999',-3) from test_add_months;
		select add_months(date '1/01/1999',-4) from test_add_months;
		select add_months(date '1/01/1999',-5) from test_add_months;
		select add_months(date '1/01/1999',-6) from test_add_months;
		select add_months(date '1/01/1999',-7) from test_add_months;
		select add_months(date '1/01/1999',-8) from test_add_months;
		select add_months(date '1/01/1999',-9) from test_add_months;
		select add_months(date '1/01/1999',-10) from test_add_months;
		select add_months(date '1/01/1999',-11) from test_add_months;
		select add_months(date '1/01/1999',-12) from test_add_months;
		select add_months(add_months_1_2,-1) from test_add_months;
		select add_months(add_months_1_2,-2) from test_add_months;
		select add_months(add_months_1_2,-3) from test_add_months;
		select add_months(add_months_1_2,-4) from test_add_months;
		select add_months(add_months_1_2,-5) from test_add_months;
		select add_months(add_months_1_2,-6) from test_add_months;
		select add_months(add_months_1_2,-7) from test_add_months;
		select add_months(add_months_1_2,-8) from test_add_months;
		select add_months(add_months_1_2,-9) from test_add_months;
		select add_months(add_months_1_2,-10) from test_add_months;
		select add_months(add_months_1_2,-11) from test_add_months;
		select add_months(add_months_1_2,-12) from test_add_months;
	select add_months(date '1/31/1999',0) from test_add_months;
	SELECT c1, 100, add_months(c1,100) FROM test_add_months;
	SELECT date '9/6/1976', i2, add_months(date '9/6/1976',i2) FROM test_add_months;
	SELECT c1, i2, add_months(c1,i2) FROM test_add_months;
	SELECT c1, i4, add_months(c1,i4) FROM test_add_months;
	SELECT c3, i2, add_months(c3,i2) FROM test_add_months;
	SELECT c3, i4, add_months(c3,i4) FROM test_add_months;
	SELECT c1, i4, add_months(NULL,i4) FROM test_add_months;
	SELECT c3, i2, add_months(c3,NULL) FROM test_add_months;
	SELECT c3, i4, add_months(NULL,NULL) FROM test_add_months;
drop table test_add_months;
rollback;
