autocommit off;
create class zz (i int, s string);
insert into zz values(1, 'yes');
select * from zz where s like null or s not like null;
select * from zz where i between 9 and null or i not between 9 and null;
select * from zz where null between null and null or null not between null and null;
select * from zz where null like null escape '_' or null not like null escape '_';
select * from zz where null = null or null <> null;
select * from zz where i+null-null*null/null > null;
select * from zz where 1/null < null or 1/null >= nulL;
select * from zz where null in {null} or null not in {null};
select * from zz where null = some(select i from zz);
select * from zz where null <> all(select null from zz);
select * from zz where s like na or s not like na;
select * from zz where i between 9 and na or i not between 9 and na;
select * from zz where na between na and na or na not between na and na;
select * from zz where na like na escape '_' or na not like na escape '_';
select * from zz where na = na or na <> na;
select * from zz where i+na-na*na/na > na;
select * from zz where 1/na < na or 1/na >= nulL;
select * from zz where na in {na} or na not in {na};
select * from zz where na = some(select i from zz);
select * from zz where na <> all(select na from zz);
rollback work;
rollback;
