autocommit off;
create class n
(sq sequence of integer,
 nsq sequence of integer,
 mst multiset,
 nmst multiset,
 st set of integer,
 nst set of integer,
 i integer,
 ni integer,
 s string,
 ns string);
create class n2
(sq sequence of integer,
 nsq sequence of integer,
 mst multiset,
 nmst multiset,
 st set of integer,
 nst set of integer,
 i integer,
 ni integer);
insert into n (sq, nsq, mst, nmst, st, nst, i, s) values
 ({3,4,5},
  {null, null, null},
  {3,4,3},
  {null, null, null},
  {5,4,3},
  {null, null, null},
  3,
  'abcdefg');
insert into n2 (sq, nsq, mst, nmst, st, nst, i) values
 ({3},
  {null},
  {3,3},
  {null, null},
  {3},
  {null},
  3);
select sq to sq1 from n;
select nsq to nsq1 from n;
select mst to mst1 from n;
select nmst to nmst1 from n;
select st to st1 from n;
select nst to nst1 from n;
select i to i1 from n;
select ni to ni1 from n;
select s to s1 from n;
select ns to ns1 from n;
select sq to sq2 from n2;
select nsq to nsq2 from n2;
select mst to mst2 from n2;
select nmst to nmst2 from n2;
select st to st2 from n2;
select nst to nst2 from n2;
select i to i2 from n2;
select ni to ni2 from n2;
select i from n where not i=3;
select i from n where not 3=3;
select i from n where not i<>3;
select i from n where not 3<>3;
select i from n where not ni = null;
select i from n where not null = null;
select i from n where not ni <> null;
select i from n where not null <> null;
select i from n where i is null;
select i from n where 3 is null;
select i from n where ni is null;
select i from n where null is null;
select i from n where sq is null;
select i from n where sq1 is null;
select i from n where nsq is null;
select i from n where nsq1 is null;
select i from n where mst is null;
select i from n where mst1 is null;
select i from n where nmst is null;
select i from n where nmst1 is null;
select i from n where st is null;
select i from n where st1 is null;
select i from n where nst is null;
select i from n where nst1 is null;
select i from n where i is not null;
select i from n where 3 is not null;
select i from n where ni is not null;
select i from n where null is not null;
select i from n where sq is not null;
select i from n where sq1 is not null;
select i from n where nsq is not null;
select i from n where nsq1 is not null;
select i from n where mst is not null;
select i from n where mst1 is not null;
select i from n where nmst is not null;
select i from n where nmst1 is not null;
select i from n where st is not null;
select i from n where st1 is not null;
select i from n where nst is not null;
select i from n where nst1 is not null;
select i from n where exists sq;
select i from n where exists sq1;
select i from n where exists nsq;
select i from n where exists nsq1;
select i from n where exists mst;
select i from n where exists mst1;
select i from n where exists nmst;
select i from n where exists nmst1;
select i from n where exists st;
select i from n where exists st1;
select i from n where exists nst;
select i from n where exists nst1;
select i from n where i=3 and i=3;
select i from n where i1=3 and i1=3;
select i from n where i=3 and i=2;
select i from n where i1=3 and i1=2;
select i from n where i=3 and i=null;
select i from n where i1=3 and i1=null;
select i from n where i=2 and i=3;
select i from n where i1=2 and i1=3;
select i from n where i=2 and i=2;
select i from n where i1=2 and i1=2;
select i from n where i=2 and i=null;
select i from n where i1=2 and i1=null;
select i from n where i=null and i=3;
select i from n where i1=null and i1=3;
select i from n where i=null and i=2;
select i from n where i1=null and i1=2;
select i from n where i=null and i=null;
select i from n where i1=null and i1=null;
select i from n where i=3 or i=3;
select i from n where i1=3 or i1=3;
select i from n where i=3 or i=2;
select i from n where i1=3 or i1=2;
select i from n where i=3 or i=null;
select i from n where i1=3 or i1=null;
select i from n where i=2 or i=3;
select i from n where i1=2 or i1=3;
select i from n where i=2 or i=2;
select i from n where i1=2 or i1=2;
select i from n where i=2 or i=null;
select i from n where i1=2 or i1=null;
select i from n where i=null or i=3;
select i from n where i1=null or i1=3;
select i from n where i=null or i=2;
select i from n where i1=null or i1=2;
select i from n where i=null or i=null;
select i from n where i1=null or i1=null;
select i from n where i=3;
select i from n where 3=3;
select i from n where i=2;
select i from n where 3=2;
select i from n where i=null;
select i from n where 3=null;
select i from n where ni=3;
select i from n where null=3;
select i from n where ni=null;
select i from n where null=null;
select i from n where sq=sq1;
select i from n where sq1=sq1;
select i from n where sq={5,6,7};
select i from n where sq1={5,6,7};
select i from n where sq=nsq1;
select i from n where sq1=nsq1;
select i from n where nsq=nsq1;
select i from n where nsq1=nsq1;
select i from n where mst=mst1;
select i from n where mst1=mst1;
select i from n where mst={5,6,7};
select i from n where mst1={5,6,7};
select i from n where mst=nmst1;
select i from n where mst1=nmst1;
select i from n where nmst=nmst1;
select i from n where nmst1=mst1;
select i from n where st=st1;
select i from n where st1=st1;
select i from n where st={5,6,7};
select i from n where st1={5,6,7};
select i from n where st=nst1;
select i from n where st1=nst1;
select i from n where nst=nst1;
select i from n where nst1=nst1;
select i from n where sq seteq sq1;
select i from n where sq1 seteq sq1;
select i from n where sq seteq {5,6,7};
select i from n where sq1 seteq {5,6,7};
select i from n where sq seteq nsq1;
select i from n where sq1 seteq nsq1;
select i from n where nsq seteq nsq1;
select i from n where nsq1 seteq nsq1;
select i from n where mst seteq mst1;
select i from n where mst1 seteq mst1;
select i from n where mst seteq {5,6,7};
select i from n where mst1 seteq {5,6,7};
select i from n where mst seteq nmst1;
select i from n where mst1 seteq nmst1;
select i from n where nmst seteq nmst1;
select i from n where nmst1 seteq mst1;
select i from n where st seteq st1;
select i from n where st1 seteq st1;
select i from n where st seteq {5,6,7};
select i from n where st1 seteq {5,6,7};
select i from n where st seteq nst1;
select i from n where st1 seteq nst1;
select i from n where nst seteq nst1;
select i from n where nst1 seteq nst1;
select i from n where i<>3;
select i from n where 3<>3;
select i from n where i<>2;
select i from n where 3<>2;
select i from n where i<>null;
select i from n where 3<>null;
select i from n where ni<>3;
select i from n where null<>3;
select i from n where ni<>null;
select i from n where null<>null;
select i from n where sq<>sq1;
select i from n where sq1<>sq1;
select i from n where sq<>{5,6,7};
select i from n where sq1<>{5,6,7};
select i from n where sq<>nsq1;
select i from n where sq1<>nsq1;
select i from n where nsq<>nsq1;
select i from n where nsq1<>nsq1;
select i from n where mst<>mst1;
select i from n where mst1<>mst1;
select i from n where mst<>{5,6,7};
select i from n where mst1<>{5,6,7};
select i from n where mst<>nmst1;
select i from n where mst1<>nmst1;
select i from n where nmst<>nmst1;
select i from n where nmst1<>mst1;
select i from n where st<>st1;
select i from n where st1<>st1;
select i from n where st<>{5,6,7};
select i from n where st1<>{5,6,7};
select i from n where st<>nst1;
select i from n where st1<>nst1;
select i from n where nst<>nst1;
select i from n where nst1<>nst1;
select i from n where sq setneq sq1;
select i from n where sq1 setneq sq1;
select i from n where sq setneq {5,6,7};
select i from n where sq1 setneq {5,6,7};
select i from n where sq setneq nsq1;
select i from n where sq1 setneq nsq1;
select i from n where nsq setneq nsq1;
select i from n where nsq1 setneq nsq1;
select i from n where mst setneq mst1;
select i from n where mst1 setneq mst1;
select i from n where mst setneq {5,6,7};
select i from n where mst1 setneq {5,6,7};
select i from n where mst setneq nmst1;
select i from n where mst1 setneq nmst1;
select i from n where nmst setneq nmst1;
select i from n where nmst1 setneq mst1;
select i from n where st setneq st1;
select i from n where st1 setneq st1;
select i from n where st setneq {5,6,7};
select i from n where st1 setneq {5,6,7};
select i from n where st setneq nst1;
select i from n where st1 setneq nst1;
select i from n where nst setneq nst1;
select i from n where nst1 setneq nst1;
select i from n where i>=3;
select i from n where 3>=3;
select i from n where i>=2;
select i from n where 3>=2;
select i from n where i>=4;
select i from n where 3>=4;
select i from n where i>=null;
select i from n where 3>=null;
select i from n where ni>=3;
select i from n where null>=3;
select i from n where ni>=null;
select i from n where null>=null;
select i from n where mst>=mst1;
select i from n where mst1>=mst1;
select i from n where mst>={3};
select i from n where mst1>={3};
select i from n where mst>={5,6,7};
select i from n where mst1>={5,6,7};
select i from n where mst>=nmst1;
select i from n where mst1>=nmst1;
select i from n where nmst>=nmst1;
select i from n where nmst1>=mst1;
select i from n where st>=st1;
select i from n where st1>=st1;
select i from n where st>={5,4};
select i from n where st1>={5,4};
select i from n where st>={5,6,7};
select i from n where st1>={5,6,7};
select i from n where st>=nst1;
select i from n where st1>=nst1;
select i from n where nst>=nst1;
select i from n where nst1>=nst1;
select i from n where mst superseteq mst1;
select i from n where mst1 superseteq mst1;
select i from n where mst superseteq {3};
select i from n where mst1 superseteq {3};
select i from n where mst superseteq {5,6,7};
select i from n where mst1 superseteq {5,6,7};
select i from n where mst superseteq nmst1;
select i from n where mst1 superseteq nmst1;
select i from n where nmst superseteq nmst1;
select i from n where nmst1 superseteq mst1;
select i from n where st superseteq st1;
select i from n where st1 superseteq st1;
select i from n where st superseteq {5,4};
select i from n where st1 superseteq {5,4};
select i from n where st superseteq {5,6,7};
select i from n where st1 superseteq {5,6,7};
select i from n where st superseteq nst1;
select i from n where st1 superseteq nst1;
select i from n where nst superseteq nst1;
select i from n where nst1 superseteq nst1;
select i from n where i>3;
select i from n where 3>3;
select i from n where i>2;
select i from n where 3>2;
select i from n where i>4;
select i from n where 3>4;
select i from n where i>null;
select i from n where 3>null;
select i from n where ni>3;
select i from n where null>3;
select i from n where ni>null;
select i from n where null>null;
select i from n where mst>mst1;
select i from n where mst1>mst1;
select i from n where mst>{3};
select i from n where mst1>{3};
select i from n where mst>{5,6,7};
select i from n where mst1>{5,6,7};
select i from n where mst>nmst1;
select i from n where mst1>nmst1;
select i from n where nmst>nmst1;
select i from n where nmst1>mst1;
select i from n where st>st1;
select i from n where st1>st1;
select i from n where st>{5,4};
select i from n where st1>{5,4};
select i from n where st>{5,6,7};
select i from n where st1>{5,6,7};
select i from n where st>nst1;
select i from n where st1>nst1;
select i from n where nst>nst1;
select i from n where nst1>nst1;
select i from n where mst superset mst1;
select i from n where mst1 superset mst1;
select i from n where mst superset {3};
select i from n where mst1 superset {3};
select i from n where mst superset {5,6,7};
select i from n where mst1 superset {5,6,7};
select i from n where mst superset nmst1;
select i from n where mst1 superset nmst1;
select i from n where nmst superset nmst1;
select i from n where nmst1 superset mst1;
select i from n where st superset st1;
select i from n where st1 superset st1;
select i from n where st superset {5,4};
select i from n where st1 superset {5,4};
select i from n where st superset {5,6,7};
select i from n where st1 superset {5,6,7};
select i from n where st superset nst1;
select i from n where st1 superset nst1;
select i from n where nst superset nst1;
select i from n where nst1 superset nst1;
select i from n where i<=3;
select i from n where 3<=3;
select i from n where i<=2;
select i from n where 3<=2;
select i from n where i<=4;
select i from n where 3<=4;
select i from n where i<=null;
select i from n where 3<=null;
select i from n where ni<=3;
select i from n where null<=3;
select i from n where ni<=null;
select i from n where null<=null;
select i from n where mst<=mst1;
select i from n where mst1<=mst1;
select i from n where mst<={3,4,3,4,3};
select i from n where mst1<={3,4,3,4,3};
select i from n where mst<={5,6,7};
select i from n where mst1<={5,6,7};
select i from n where mst<=nmst1;
select i from n where mst1<=nmst1;
select i from n where nmst<=nmst1;
select i from n where nmst1<=mst1;
select i from n where st<=st1;
select i from n where st1<=st1;
select i from n where st<={6,5,4,3,2};
select i from n where st1<={6,5,4,3,2};
select i from n where st<={5,6,7};
select i from n where st1<={5,6,7};
select i from n where st<=nst1;
select i from n where st1<=nst1;
select i from n where nst<=nst1;
select i from n where nst1<=nst1;
select i from n where mst subseteq mst1;
select i from n where mst1 subseteq mst1;
select i from n where mst subseteq {3,4,3,4,3};
select i from n where mst1 subseteq {3,4,3,4,3};
select i from n where mst subseteq {5,6,7};
select i from n where mst1 subseteq {5,6,7};
select i from n where mst subseteq nmst1;
select i from n where mst1 subseteq nmst1;
select i from n where nmst subseteq nmst1;
select i from n where nmst1 subseteq mst1;
select i from n where st subseteq st1;
select i from n where st1 subseteq st1;
select i from n where st subseteq {6,5,4,3,2};
select i from n where st1 subseteq {6,5,4,3,2};
select i from n where st subseteq {5,6,7};
select i from n where st1 subseteq {5,6,7};
select i from n where st subseteq nst1;
select i from n where st1 subseteq nst1;
select i from n where nst subseteq nst1;
select i from n where nst1 subseteq nst1;
select i from n where i<3;
select i from n where 3<3;
select i from n where i<2;
select i from n where 3<2;
select i from n where i<4;
select i from n where 3<4;
select i from n where i<null;
select i from n where 3<null;
select i from n where ni<3;
select i from n where null<3;
select i from n where ni<null;
select i from n where null<null;
select i from n where mst<mst1;
select i from n where mst1<mst1;
select i from n where mst<{3,4,3,4,3};
select i from n where mst1<{3,4,3,4,3};
select i from n where mst<{5,6,7};
select i from n where mst1<{5,6,7};
select i from n where mst<nmst1;
select i from n where mst1<nmst1;
select i from n where nmst<nmst1;
select i from n where nmst1<mst1;
select i from n where st<st1;
select i from n where st1<st1;
select i from n where st<{6,5,4,3,2};
select i from n where st1<{6,5,4,3,2};
select i from n where st<{5,6,7};
select i from n where st1<{5,6,7};
select i from n where st<nst1;
select i from n where st1<nst1;
select i from n where nst<nst1;
select i from n where nst1<nst1;
select i from n where mst subset mst1;
select i from n where mst1 subset mst1;
select i from n where mst subset {3,4,3,4,3};
select i from n where mst1 subset {3,4,3,4,3};
select i from n where mst subset {5,6,7};
select i from n where mst1 subset {5,6,7};
select i from n where mst subset nmst1;
select i from n where mst1 subset nmst1;
select i from n where nmst subset nmst1;
select i from n where nmst1 subset mst1;
select i from n where st subset st1;
select i from n where st1 subset st1;
select i from n where st subset {6,5,4,3,2};
select i from n where st1 subset {6,5,4,3,2};
select i from n where st subset {5,6,7};
select i from n where st1 subset {5,6,7};
select i from n where st subset nst1;
select i from n where st1 subset nst1;
select i from n where nst subset nst1;
select i from n where nst1 subset nst1;
select i from n where i in sq;
select i from n where 3 in sq1;
select i from n where i+4 in sq;
select i from n where 7 in sq1;
select i from n where ni in sq;
select i from n where null in sq1;
select i from n where i in nsq;
select i from n where 3 in nsq1;
select i from n where ni in nsq;
select i from n where null in nsq1;
select i from n where i in mst;
select i from n where 3 in mst1;
select i from n where i+4 in mst;
select i from n where 7 in mst1;
select i from n where ni in mst;
select i from n where null in mst1;
select i from n where i in nmst;
select i from n where 3 in nmst1;
select i from n where ni in nmst;
select i from n where null in nmst1;
select i from n where i in st;
select i from n where 3 in st1;
select i from n where i+4 in st;
select i from n where 7 in st1;
select i from n where ni in st;
select i from n where null in st1;
select i from n where i in nst;
select i from n where 3 in nst1;
select i from n where ni in nst;
select i from n where null in nst1;
select i from n where i = some sq;
select i from n where 3 = some sq1;
select i from n where i+4 = some sq;
select i from n where 7 = some sq1;
select i from n where ni = some sq;
select i from n where null = some sq1;
select i from n where i = some nsq;
select i from n where 3 = some nsq1;
select i from n where ni = some nsq;
select i from n where null = some nsq1;
select i from n where i = some mst;
select i from n where 3 = some mst1;
select i from n where i+4 = some mst;
select i from n where 7 = some mst1;
select i from n where ni = some mst;
select i from n where null = some mst1;
select i from n where i = some nmst;
select i from n where 3 = some nmst1;
select i from n where ni = some nmst;
select i from n where null = some nmst1;
select i from n where i = some st;
select i from n where 3 = some st1;
select i from n where i+4 = some st;
select i from n where 7 = some st1;
select i from n where ni = some st;
select i from n where null = some st1;
select i from n where i = some nst;
select i from n where 3 = some nst1;
select i from n where ni = some nst;
select i from n where null = some nst1;
select i from n where i <> some sq;
select i from n where 3 <> some sq1;
select i from n where i+4 <> some sq;
select i from n where 7 <> some sq1;
select i from n where ni <> some sq;
select i from n where null <> some sq1;
select i from n where i <> some nsq;
select i from n where 3 <> some nsq1;
select i from n where ni <> some nsq;
select i from n where null <> some nsq1;
select i from n where i <> some mst;
select i from n where 3 <> some mst1;
select i from n where i+4 <> some mst;
select i from n where 7 <> some mst1;
select i from n where ni <> some mst;
select i from n where null <> some mst1;
select i from n where i <> some nmst;
select i from n where 3 <> some nmst1;
select i from n where ni <> some nmst;
select i from n where null <> some nmst1;
select i from n where i <> some st;
select i from n where 3 <> some st1;
select i from n where i+4 <> some st;
select i from n where 7 <> some st1;
select i from n where ni <> some st;
select i from n where null <> some st1;
select i from n where i <> some nst;
select i from n where 3 <> some nst1;
select i from n where ni <> some nst;
select i from n where null <> some nst1;
select i from n where i >= some sq;
select i from n where 3 >= some sq1;
select i from n where i+4 >= some sq;
select i from n where 7 >= some sq1;
select i from n where i-2 >= some sq;
select i from n where 1 >= some sq1;
select i from n where ni >= some sq;
select i from n where null >= some sq1;
select i from n where i >= some nsq;
select i from n where 3 >= some nsq1;
select i from n where ni >= some nsq;
select i from n where null >= some nsq1;
select i from n where i >= some mst;
select i from n where 3 >= some mst1;
select i from n where i+4 >= some mst;
select i from n where 7 >= some mst1;
select i from n where i-2 >= some mst;
select i from n where 1 >= some mst1;
select i from n where ni >= some mst;
select i from n where null >= some mst1;
select i from n where i >= some nmst;
select i from n where 3 >= some nmst1;
select i from n where ni >= some nmst;
select i from n where null >= some nmst1;
select i from n where i >= some st;
select i from n where 3 >= some st1;
select i from n where i+4 >= some st;
select i from n where 7 >= some st1;
select i from n where i-2 >= some st;
select i from n where 1 >= some st1;
select i from n where ni >= some st;
select i from n where null >= some st1;
select i from n where i >= some nst;
select i from n where 3 >= some nst1;
select i from n where ni >= some nst;
select i from n where null >= some nst1;
select i from n where i > some sq;
select i from n where 3 > some sq1;
select i from n where i+4 > some sq;
select i from n where 7 > some sq1;
select i from n where i-2 > some sq;
select i from n where 1 > some sq1;
select i from n where ni > some sq;
select i from n where null > some sq1;
select i from n where i > some nsq;
select i from n where 3 > some nsq1;
select i from n where ni > some nsq;
select i from n where null > some nsq1;
select i from n where i > some mst;
select i from n where 3 > some mst1;
select i from n where i+4 > some mst;
select i from n where 7 > some mst1;
select i from n where i-2 > some mst;
select i from n where 1 > some mst1;
select i from n where ni > some mst;
select i from n where null > some mst1;
select i from n where i > some nmst;
select i from n where 3 > some nmst1;
select i from n where ni > some nmst;
select i from n where null > some nmst1;
select i from n where i > some st;
select i from n where 3 > some st1;
select i from n where i+4 > some st;
select i from n where 7 > some st1;
select i from n where i-2 > some st;
select i from n where 1 > some st1;
select i from n where ni > some st;
select i from n where null > some st1;
select i from n where i > some nst;
select i from n where 3 > some nst1;
select i from n where ni > some nst;
select i from n where null > some nst1;
select i from n where i <= some sq;
select i from n where 3 <= some sq1;
select i from n where i+4 <= some sq;
select i from n where 7 <= some sq1;
select i from n where i-2 <= some sq;
select i from n where 1 <= some sq1;
select i from n where ni <= some sq;
select i from n where null <= some sq1;
select i from n where i <= some nsq;
select i from n where 3 <= some nsq1;
select i from n where ni <= some nsq;
select i from n where null <= some nsq1;
select i from n where i <= some mst;
select i from n where 3 <= some mst1;
select i from n where i+4 <= some mst;
select i from n where 7 <= some mst1;
select i from n where i-2 <= some mst;
select i from n where 1 <= some mst1;
select i from n where ni <= some mst;
select i from n where null <= some mst1;
select i from n where i <= some nmst;
select i from n where 3 <= some nmst1;
select i from n where ni <= some nmst;
select i from n where null <= some nmst1;
select i from n where i <= some st;
select i from n where 3 <= some st1;
select i from n where i+4 <= some st;
select i from n where 7 <= some st1;
select i from n where i-2 <= some st;
select i from n where 1 <= some st1;
select i from n where ni <= some st;
select i from n where null <= some st1;
select i from n where i <= some nst;
select i from n where 3 <= some nst1;
select i from n where ni <= some nst;
select i from n where null <= some nst1;
select i from n where i < some sq;
select i from n where 3 < some sq1;
select i from n where i+4 < some sq;
select i from n where 7 < some sq1;
select i from n where i-2 < some sq;
select i from n where 1 < some sq1;
select i from n where ni < some sq;
select i from n where null < some sq1;
select i from n where i < some nsq;
select i from n where 3 < some nsq1;
select i from n where ni < some nsq;
select i from n where null < some nsq1;
select i from n where i < some mst;
select i from n where 3 < some mst1;
select i from n where i+4 < some mst;
select i from n where 7 < some mst1;
select i from n where i-2 < some mst;
select i from n where 1 < some mst1;
select i from n where ni < some mst;
select i from n where null < some mst1;
select i from n where i < some nmst;
select i from n where 3 < some nmst1;
select i from n where ni < some nmst;
select i from n where null < some nmst1;
select i from n where i < some st;
select i from n where 3 < some st1;
select i from n where i+4 < some st;
select i from n where 7 < some st1;
select i from n where i-2 < some st;
select i from n where 1 < some st1;
select i from n where ni < some st;
select i from n where null < some st1;
select i from n where i < some nst;
select i from n where 3 < some nst1;
select i from n where ni < some nst;
select i from n where null < some nst1;
select i from n where i = all sq;
select i from n where 3 = all sq1;
select i from n where i+4 = all sq;
select i from n where 7 = all sq1;
select i from n where i-2 = all sq;
select i from n where 1 = all sq1;
select i from n where ni = all sq;
select i from n where null = all sq1;
select i from n where i = all nsq;
select i from n where 3 = all nsq1;
select i from n where ni = all nsq;
select i from n where null = all nsq1;
select i from n where i = all mst;
select i from n where 3 = all mst1;
select i from n where i+4 = all mst;
select i from n where 7 = all mst1;
select i from n where i-2 = all mst;
select i from n where 1 = all mst1;
select i from n where ni = all mst;
select i from n where null = all mst1;
select i from n where i = all nmst;
select i from n where 3 = all nmst1;
select i from n where ni = all nmst;
select i from n where null = all nmst1;
select i from n where i = all st;
select i from n where 3 = all st1;
select i from n where i+4 = all st;
select i from n where 7 = all st1;
select i from n where i-2 = all st;
select i from n where 1 = all st1;
select i from n where ni = all st;
select i from n where null = all st1;
select i from n where i = all nst;
select i from n where 3 = all nst1;
select i from n where ni = all nst;
select i from n where null = all nst1;
select i from n2 where i = all sq;
select i from n2 where 3 = all sq2;
select i from n2 where i+4 = all sq;
select i from n2 where 7 = all sq2;
select i from n2 where i-2 = all sq;
select i from n2 where 1 = all sq2;
select i from n2 where ni = all sq;
select i from n2 where null = all sq2;
select i from n2 where i = all nsq;
select i from n2 where 3 = all nsq2;
select i from n2 where ni = all nsq;
select i from n2 where null = all nsq2;
select i from n2 where i = all mst;
select i from n2 where 3 = all mst2;
select i from n2 where i+4 = all mst;
select i from n2 where 7 = all mst2;
select i from n2 where i-2 = all mst;
select i from n2 where 1 = all mst2;
select i from n2 where ni = all mst;
select i from n2 where null = all mst2;
select i from n2 where i = all nmst;
select i from n2 where 3 = all nmst2;
select i from n2 where ni = all nmst;
select i from n2 where null = all nmst2;
select i from n2 where i = all st;
select i from n2 where 3 = all st2;
select i from n2 where i+4 = all st;
select i from n2 where 7 = all st2;
select i from n2 where i-2 = all st;
select i from n2 where 1 = all st2;
select i from n2 where ni = all st;
select i from n2 where null = all st2;
select i from n2 where i = all nst;
select i from n2 where 3 = all nst2;
select i from n2 where ni = all nst;
select i from n2 where null = all nst2;
select i from n where i <> all sq;
select i from n where 3 <> all sq1;
select i from n where i+4 <> all sq;
select i from n where 7 <> all sq1;
select i from n where i-2 <> all sq;
select i from n where 1 <> all sq1;
select i from n where ni <> all sq;
select i from n where null <> all sq1;
select i from n where i <> all nsq;
select i from n where 3 <> all nsq1;
select i from n where ni <> all nsq;
select i from n where null <> all nsq1;
select i from n where i <> all mst;
select i from n where 3 <> all mst1;
select i from n where i+4 <> all mst;
select i from n where 7 <> all mst1;
select i from n where i-2 <> all mst;
select i from n where 1 <> all mst1;
select i from n where ni <> all mst;
select i from n where null <> all mst1;
select i from n where i <> all nmst;
select i from n where 3 <> all nmst1;
select i from n where ni <> all nmst;
select i from n where null <> all nmst1;
select i from n where i <> all st;
select i from n where 3 <> all st1;
select i from n where i+4 <> all st;
select i from n where 7 <> all st1;
select i from n where i-2 <> all st;
select i from n where 1 <> all st1;
select i from n where ni <> all st;
select i from n where null <> all st1;
select i from n where i <> all nst;
select i from n where 3 <> all nst1;
select i from n where ni <> all nst;
select i from n where null <> all nst1;
select i from n where i not in sq;
select i from n where 3 not in sq1;
select i from n where i+4 not in sq;
select i from n where 7 not in sq1;
select i from n where i-2 not in sq;
select i from n where 1 not in sq1;
select i from n where ni not in sq;
select i from n where null not in sq1;
select i from n where i not in nsq;
select i from n where 3 not in nsq1;
select i from n where ni not in nsq;
select i from n where null not in nsq1;
select i from n where i not in mst;
select i from n where 3 not in mst1;
select i from n where i+4 not in mst;
select i from n where 7 not in mst1;
select i from n where i-2 not in mst;
select i from n where 1 not in mst1;
select i from n where ni not in mst;
select i from n where null not in mst1;
select i from n where i not in nmst;
select i from n where 3 not in nmst1;
select i from n where ni not in nmst;
select i from n where null not in nmst1;
select i from n where i not in st;
select i from n where 3 not in st1;
select i from n where i+4 not in st;
select i from n where 7 not in st1;
select i from n where i-2 not in st;
select i from n where 1 not in st1;
select i from n where ni not in st;
select i from n where null not in st1;
select i from n where i not in nst;
select i from n where 3 not in nst1;
select i from n where ni not in nst;
select i from n where null not in nst1;
select i from n where i >= all sq;
select i from n where 3 >= all sq1;
select i from n where i+4 >= all sq;
select i from n where 7 >= all sq1;
select i from n where i-2 >= all sq;
select i from n where 1 >= all sq1;
select i from n where ni >= all sq;
select i from n where null >= all sq1;
select i from n where i >= all nsq;
select i from n where 3 >= all nsq1;
select i from n where ni >= all nsq;
select i from n where null >= all nsq1;
select i from n where i >= all mst;
select i from n where 3 >= all mst1;
select i from n where i+4 >= all mst;
select i from n where 7 >= all mst1;
select i from n where i-2 >= all mst;
select i from n where 1 >= all mst1;
select i from n where ni >= all mst;
select i from n where null >= all mst1;
select i from n where i >= all nmst;
select i from n where 3 >= all nmst1;
select i from n where ni >= all nmst;
select i from n where null >= all nmst1;
select i from n where i >= all st;
select i from n where 3 >= all st1;
select i from n where i+4 >= all st;
select i from n where 7 >= all st1;
select i from n where i-2 >= all st;
select i from n where 1 >= all st1;
select i from n where ni >= all st;
select i from n where null >= all st1;
select i from n where i >= all nst;
select i from n where 3 >= all nst1;
select i from n where ni >= all nst;
select i from n where null >= all nst1;
select i from n where i > all sq;
select i from n where 3 > all sq1;
select i from n where i+4 > all sq;
select i from n where 7 > all sq1;
select i from n where i-2 > all sq;
select i from n where 1 > all sq1;
select i from n where ni > all sq;
select i from n where null > all sq1;
select i from n where i > all nsq;
select i from n where 3 > all nsq1;
select i from n where ni > all nsq;
select i from n where null > all nsq1;
select i from n where i > all mst;
select i from n where 3 > all mst1;
select i from n where i+4 > all mst;
select i from n where 7 > all mst1;
select i from n where i-2 > all mst;
select i from n where 1 > all mst1;
select i from n where ni > all mst;
select i from n where null > all mst1;
select i from n where i > all nmst;
select i from n where 3 > all nmst1;
select i from n where ni > all nmst;
select i from n where null > all nmst1;
select i from n where i > all st;
select i from n where 3 > all st1;
select i from n where i+4 > all st;
select i from n where 7 > all st1;
select i from n where i-2 > all st;
select i from n where 1 > all st1;
select i from n where ni > all st;
select i from n where null > all st1;
select i from n where i > all nst;
select i from n where 3 > all nst1;
select i from n where ni > all nst;
select i from n where null > all nst1;
select i from n where i <= all sq;
select i from n where 3 <= all sq1;
select i from n where i+4 <= all sq;
select i from n where 7 <= all sq1;
select i from n where i-2 <= all sq;
select i from n where 1 <= all sq1;
select i from n where ni <= all sq;
select i from n where null <= all sq1;
select i from n where i <= all nsq;
select i from n where 3 <= all nsq1;
select i from n where ni <= all nsq;
select i from n where null <= all nsq1;
select i from n where i <= all mst;
select i from n where 3 <= all mst1;
select i from n where i+4 <= all mst;
select i from n where 7 <= all mst1;
select i from n where i-2 <= all mst;
select i from n where 1 <= all mst1;
select i from n where ni <= all mst;
select i from n where null <= all mst1;
select i from n where i <= all nmst;
select i from n where 3 <= all nmst1;
select i from n where ni <= all nmst;
select i from n where null <= all nmst1;
select i from n where i <= all st;
select i from n where 3 <= all st1;
select i from n where i+4 <= all st;
select i from n where 7 <= all st1;
select i from n where i-2 <= all st;
select i from n where 1 <= all st1;
select i from n where ni <= all st;
select i from n where null <= all st1;
select i from n where i <= all nst;
select i from n where 3 <= all nst1;
select i from n where ni <= all nst;
select i from n where null <= all nst1;
select i from n where i < all sq;
select i from n where 3 < all sq1;
select i from n where i+4 < all sq;
select i from n where 7 < all sq1;
select i from n where i-2 < all sq;
select i from n where 1 < all sq1;
select i from n where ni < all sq;
select i from n where null < all sq1;
select i from n where i < all nsq;
select i from n where 3 < all nsq1;
select i from n where ni < all nsq;
select i from n where null < all nsq1;
select i from n where i < all mst;
select i from n where 3 < all mst1;
select i from n where i+4 < all mst;
select i from n where 7 < all mst1;
select i from n where i-2 < all mst;
select i from n where 1 < all mst1;
select i from n where ni < all mst;
select i from n where null < all mst1;
select i from n where i < all nmst;
select i from n where 3 < all nmst1;
select i from n where ni < all nmst;
select i from n where null < all nmst1;
select i from n where i < all st;
select i from n where 3 < all st1;
select i from n where i+4 < all st;
select i from n where 7 < all st1;
select i from n where i-2 < all st;
select i from n where 1 < all st1;
select i from n where ni < all st;
select i from n where null < all st1;
select i from n where i < all nst;
select i from n where 3 < all nst1;
select i from n where ni < all nst;
select i from n where null < all nst1;
select i from n where s like '%de_g';
select i from n where s1 like '%de_g';
select i from n where s like '%de_gh';
select i from n where s1 like '%de_gh';
select i from n where s like null;
select i from n where s1 like null;
select i from n where ns like '%de_g';
select i from n where ns1 like '%de_g';
select i from n where ns like null;
select i from n where ns1 like null;
select i from n where s not like '%de_g';
select i from n where s1 not like '%de_g';
select i from n where s not like '%de_gh';
select i from n where s1 not like '%de_gh';
select i from n where s not like null;
select i from n where s1 not like null;
select i from n where ns not like '%de_g';
select i from n where ns1 not like '%de_g';
select i from n where ns not like null;
select i from n where ns1 not like null;
select i from n where i between 3 and 3;
select i from n where 3 between 3 and 3;
select i from n where i between 2 and 3;
select i from n where 3 between 2 and 3;
select i from n where i between 4 and 3;
select i from n where 3 between 4 and 3;
select i from n where i between null and 3;
select i from n where 3 between null and 3;
select i from n where ni between 3 and 3;
select i from n where null between 3 and 3;
select i from n where ni between null and 3;
select i from n where null between null and 3;
select i from n where ni between null and null;
select i from n where null between null and null;
select i from n where mst between mst1 and mst1;
select i from n where mst1 between mst1 and mst1;
select i from n where mst between {3,3} and {3,4,3,4,3};
select i from n where mst1 between {3,3} and {3,4,3,4,3};
select i from n where mst between {3,3} and {5,6,7};
select i from n where mst1 between {3,3} and {5,6,7};
select i from n where mst between nmst1 and mst1;
select i from n where mst1 between nmst1 and mst1;
select i from n where nmst between nmst1 and nmst1;
select i from n where nmst1 between nmst1 and nmst1;
select i from n where st between st1 and st1;
select i from n where st1 between st1 and st1;
select i from n where st between {3,4} and {6,5,4,3,2};
select i from n where st1 between {3,4} and {6,5,4,3,2};
select i from n where st between {3,4} and {5,6,7};
select i from n where st1 between {3,4} and {5,6,7};
select i from n where st between nst1 and st1;
select i from n where st1 between nst1 and st1;
select i from n where nst between nst1 and nst1;
select i from n where nst1 between nst1 and nst1;
select i from n where i not between 3 and 3;
select i from n where 3 not between 3 and 3;
select i from n where i not between 2 and 3;
select i from n where 3 not between 2 and 3;
select i from n where i not between 4 and 3;
select i from n where 3 not between 4 and 3;
select i from n where i not between null and 3;
select i from n where 3 not between null and 3;
select i from n where ni not between 3 and 3;
select i from n where null not between 3 and 3;
select i from n where ni not between null and 3;
select i from n where null not between null and 3;
select i from n where ni not between null and null;
select i from n where null not between null and null;
select i from n where mst not between mst1 and mst1;
select i from n where mst1 not between mst1 and mst1;
select i from n where mst not between {3,3} and {3,4,3,4,3};
select i from n where mst1 not between {3,3} and {3,4,3,4,3};
select i from n where mst not between {3,3} and {5,6,7};
select i from n where mst1 not between {3,3} and {5,6,7};
select i from n where mst not between nmst1 and mst1;
select i from n where mst1 not between nmst1 and mst1;
select i from n where nmst not between nmst1 and nmst1;
select i from n where nmst1 not between nmst1 and nmst1;
select i from n where st not between st1 and st1;
select i from n where st1 not between st1 and st1;
select i from n where st not between {3,4} and {6,5,4,3,2};
select i from n where st1 not between {3,4} and {6,5,4,3,2};
select i from n where st not between {3,4} and {5,6,7};
select i from n where st1 not between {3,4} and {5,6,7};
select i from n where st not between nst1 and st1;
select i from n where st1 not between nst1 and st1;
select i from n where nst not between nst1 and nst1;
select i from n where nst1 not between nst1 and nst1;
rollback work;
rollback;
