autocommit off;
create table nljn (a int, b int);
create serial nla;
create serial nlb start with 1000 increment by -1;
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.next_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
insert into nljn values(nla.current_value, nlb.next_value);
create index i_nljn_a_b on nljn(a, b);
update statistics on nljn;
select /*+ ORDERED */ x.a, x.b 
from nljn x, nljn y 
where x.a = 1 and x.a = y.a and y.b > 995 
using index x.i_nljn_a_b(+), y.i_nljn_a_b(+) order by 1,2;

rollback;
