autocommit off;
--set optimization: level 257;
create class w (a int, b int, c int);
create class x (a int, b int, c int);
create class y (a int, b int, c int);
create class z (a int, b int, c int);
insert into w values (1, 11, 101);
insert into w values (2, 12, 102);
insert into w values (3, 13, 103);
insert into w values (4, 14, 104);
insert into w values (5, 15, 105);
insert into x select * from w;
insert into y select * from w;
insert into z select * from w;
select count(*) from w, x, y where x.a = y.a; 
select count(*) from w, x, y, z where w.a = x.a and y.b = z.b;
select count(*) from w, x, y, z where w.a = y.a and x.b = z.b;
select count(*) from w, x, y, z where x.a = y.a and y.b = z.b;
select count(*) from w, x left join y on x.a = y.a;
select count(*) from w left join x on w.a = x.a, y left join z on y.b = z.b;
select count(*) from w left join y on w.a = y.a, x, z where x.b = z.b;
select count(*) from w, x left join y on x.a = y.a left join z on y.b = z.b;
rollback work;
rollback;
