autocommit off;
create class bar (c int, d int);
create class foo class attribute (ca int, cb bar) (a int, b bar);
insert into bar values (3, 4) into :id;
insert into foo values (1, :id);
select a, b.d, class foo.ca, class foo.cb.c from foo;
select foo.a, foo.b.d, class foo.ca, class foo.cb.c from foo;
select a, b.d, class foo.ca, class foo.cb.c from foo x;
select x.a, x.b.d, class foo.ca, class foo.cb.c from foo x;
select a, b.d, class foo.ca, class foo.cb.c, foo.* from foo;
select foo.a, foo.b.d, class foo.ca, class foo.cb.c, foo.* from foo;
select a, b.d, class foo.ca, class foo.cb.c, x.* from foo x;
select x.a, x.b.d, class foo.ca, class foo.cb.c, x.* from foo x;
select a p, b.d q, class foo.ca r, class foo.cb.c s from foo;
select foo.a p, foo.b.d q, class foo.ca r, class foo.cb.c s from foo;
select a p, b.d q, class foo.ca r, class foo.cb.c s from foo x;
select x.a p, x.b.d q, class foo.ca r, class foo.cb.c s from foo x;
select a p, b.d q, class foo.ca r, class foo.cb.c s, foo.* from foo;
select foo.a p, foo.b.d q, class foo.ca r, class foo.cb.c s, foo.* from foo;
select a p, b.d q, class foo.ca r, class foo.cb.c s, x.* from foo x;
select x.a p, x.b.d q, class foo.ca r, class foo.cb.c s, x.* from foo x; 
select 2 from foo;
select 2 p from foo;
select * from foo;
rollback work;
rollback;
