autocommit off;
create class foo (x char(2));
insert into foo values ('1');
insert into foo values ('2');
insert into foo values ('3');
insert into foo values ('4');
insert into foo values ('5');
insert into foo values ('6');
insert into foo values ('7');
insert into foo values ('8');
insert into foo values ('9');
insert into foo values ('a');
insert into foo values ('b');
insert into foo select trim(x) + '1' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '2' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '3' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '4' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '5' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '6' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '7' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '8' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + '9' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + 'a' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + 'b' from foo where char_length(trim(x)) = 1;
insert into foo select trim(x) + 'c' from foo where char_length(trim(x)) = 1;
create index i_foo_x on foo(x);
select * from foo where x >= 'b';
rollback;
