autocommit off;
use gdb;
create class one(a int);
savepoint 1;
insert into one values(100);
select * from one;
savepoint '2'; 
insert into one values(200);
select * from one;
savepoint aaa; 
insert into one values(300);
select * from one;
rollback to savepoint aaa;
select * from one;
rollback to savepoint '2';
select * from one;
rollback to savepoint 1;
select * from one;
rollback;
