autocommit off;
create class foo (id int, sq sequence(int, string));
insert into foo values (-1, NULL);
insert into foo values (0, {});
insert into foo values (2, {1});
insert into foo values (3, {2});
insert into foo values (7, {0, 1});
insert into foo values (8, {0, 2});
insert into foo values (9, {1, 1});
insert into foo values (15, {1, 1, 1});
insert into foo values (5, {'a'});
insert into foo values (1, {NULL});
insert into foo values (6, {'b'});
insert into foo values (13, {'a', 'b'});
insert into foo values (12, {'a', 'a'});
insert into foo values (11, {'a', 1});
insert into foo values (10, {1, 'a'});
insert into foo values (14, {NULL, NULL, NULL});
insert into foo values (4, {'A'});
select * from foo order by sq;
select * from foo where sq <> sequence{1, 1} order by id;
rollback;
