autocommit off;
create class x (intseq sequence(int));
create class y (strseq sequence(string));
create class z (mseq sequence());
insert into x values ({1, 2, 3, 4});
insert into y values ({'1', '2', '3'});
insert into z values ({1, '2', 3, '4'});
select u from x, table(intseq) as t(u);
select u from y, table(strseq) as t(u);
select * from z;
update x set intseq = intseq + sequence{5, 6};
update y set strseq = strseq + sequence{'4', '5'};
update z set mseq = mseq + sequence{5, '6'};
select u from x, table(intseq) as t(u);
select u from y, table(strseq) as t(u);
select * from z;
update x set intseq = sequence{1, 2} + sequence{7, 8};
update y set strseq = sequence{'1', '2'} + sequence{'6', '7', '8'};
update z set mseq = sequence{1, '2'} + sequence{7, '8'};
select u from x, table(intseq) as t(u);
select u from y, table(strseq) as t(u);
select * from z;
update x set intseq = sequence{1, NULL, 2} + sequence{NULL, 7, 8};
update y set strseq = sequence{'1', NULL, '2'} + sequence{'6', '7', NULL, '8'};
update z set mseq = sequence{1, NULL, '2'} + sequence{7, '8', NULL};
select * from x;
select u from x, table(intseq) as t(u);
select * from y;
select u from y, table(strseq) as t(u);
select * from z;
rollback work;
rollback;
