--+ holdcas on;

create table t1 (hex_cp char(4), unicode_cp int , utf8_enc string collate utf8_de_exp, s1 string collate utf8_bin);

-- all codepoints having UCA weights levels 1-3 = zero
INSERT INTO t1 (hex_cp) values('0000');
INSERT INTO t1 (hex_cp) values('0001');
INSERT INTO t1 (hex_cp) values('0002');
INSERT INTO t1 (hex_cp) values('0003');
INSERT INTO t1 (hex_cp) values('0004');
INSERT INTO t1 (hex_cp) values('0005');
INSERT INTO t1 (hex_cp) values('0006');
INSERT INTO t1 (hex_cp) values('0007');
INSERT INTO t1 (hex_cp) values('0008');
INSERT INTO t1 (hex_cp) values('000E');
INSERT INTO t1 (hex_cp) values('000F');
INSERT INTO t1 (hex_cp) values('0010');
INSERT INTO t1 (hex_cp) values('0011');
INSERT INTO t1 (hex_cp) values('0012');
INSERT INTO t1 (hex_cp) values('0013');
INSERT INTO t1 (hex_cp) values('0014');
INSERT INTO t1 (hex_cp) values('0015');
INSERT INTO t1 (hex_cp) values('0016');
INSERT INTO t1 (hex_cp) values('0017');
INSERT INTO t1 (hex_cp) values('0018');
INSERT INTO t1 (hex_cp) values('0019');
INSERT INTO t1 (hex_cp) values('001A');
INSERT INTO t1 (hex_cp) values('001B');
INSERT INTO t1 (hex_cp) values('001C');
INSERT INTO t1 (hex_cp) values('001D');
INSERT INTO t1 (hex_cp) values('001E');
INSERT INTO t1 (hex_cp) values('001F');
INSERT INTO t1 (hex_cp) values('0020');
INSERT INTO t1 (hex_cp) values('007F');
INSERT INTO t1 (hex_cp) values('0080');
INSERT INTO t1 (hex_cp) values('0081');
INSERT INTO t1 (hex_cp) values('0082');
INSERT INTO t1 (hex_cp) values('0083');
INSERT INTO t1 (hex_cp) values('0084');
INSERT INTO t1 (hex_cp) values('0086');
INSERT INTO t1 (hex_cp) values('0087');
INSERT INTO t1 (hex_cp) values('0088');
INSERT INTO t1 (hex_cp) values('0089');
INSERT INTO t1 (hex_cp) values('008A');
INSERT INTO t1 (hex_cp) values('008B');
INSERT INTO t1 (hex_cp) values('008C');
INSERT INTO t1 (hex_cp) values('008D');
INSERT INTO t1 (hex_cp) values('008E');
INSERT INTO t1 (hex_cp) values('008F');
INSERT INTO t1 (hex_cp) values('0090');
INSERT INTO t1 (hex_cp) values('0091');
INSERT INTO t1 (hex_cp) values('0092');
INSERT INTO t1 (hex_cp) values('0093');
INSERT INTO t1 (hex_cp) values('0094');
INSERT INTO t1 (hex_cp) values('0095');
INSERT INTO t1 (hex_cp) values('0096');
INSERT INTO t1 (hex_cp) values('0097');
INSERT INTO t1 (hex_cp) values('0098');
INSERT INTO t1 (hex_cp) values('0099');
INSERT INTO t1 (hex_cp) values('009A');
INSERT INTO t1 (hex_cp) values('009B');
INSERT INTO t1 (hex_cp) values('009C');
INSERT INTO t1 (hex_cp) values('009D');
INSERT INTO t1 (hex_cp) values('009E');
INSERT INTO t1 (hex_cp) values('009F');
INSERT INTO t1 (hex_cp) values('00AD');
INSERT INTO t1 (hex_cp) values('034F');
INSERT INTO t1 (hex_cp) values('0488');
INSERT INTO t1 (hex_cp) values('0489');
INSERT INTO t1 (hex_cp) values('0591');
INSERT INTO t1 (hex_cp) values('0592');
INSERT INTO t1 (hex_cp) values('0593');
INSERT INTO t1 (hex_cp) values('0594');
INSERT INTO t1 (hex_cp) values('0595');
INSERT INTO t1 (hex_cp) values('0596');
INSERT INTO t1 (hex_cp) values('0597');
INSERT INTO t1 (hex_cp) values('0598');
INSERT INTO t1 (hex_cp) values('0599');
INSERT INTO t1 (hex_cp) values('059A');
INSERT INTO t1 (hex_cp) values('059B');
INSERT INTO t1 (hex_cp) values('059C');
INSERT INTO t1 (hex_cp) values('059D');
INSERT INTO t1 (hex_cp) values('059E');
INSERT INTO t1 (hex_cp) values('059F');
INSERT INTO t1 (hex_cp) values('05A0');
INSERT INTO t1 (hex_cp) values('05A1');
INSERT INTO t1 (hex_cp) values('05A2');
INSERT INTO t1 (hex_cp) values('05A3');
INSERT INTO t1 (hex_cp) values('05A4');
INSERT INTO t1 (hex_cp) values('05A5');
INSERT INTO t1 (hex_cp) values('05A6');
INSERT INTO t1 (hex_cp) values('05A7');
INSERT INTO t1 (hex_cp) values('05A8');
INSERT INTO t1 (hex_cp) values('05A9');
INSERT INTO t1 (hex_cp) values('05AA');
INSERT INTO t1 (hex_cp) values('05AB');
INSERT INTO t1 (hex_cp) values('05AC');
INSERT INTO t1 (hex_cp) values('05AD');
INSERT INTO t1 (hex_cp) values('05AE');
INSERT INTO t1 (hex_cp) values('05AF');
INSERT INTO t1 (hex_cp) values('05BD');
INSERT INTO t1 (hex_cp) values('05C4');
INSERT INTO t1 (hex_cp) values('05C5');
INSERT INTO t1 (hex_cp) values('0600');
INSERT INTO t1 (hex_cp) values('0601');
INSERT INTO t1 (hex_cp) values('0602');
INSERT INTO t1 (hex_cp) values('0603');
INSERT INTO t1 (hex_cp) values('0610');
INSERT INTO t1 (hex_cp) values('0611');
INSERT INTO t1 (hex_cp) values('0612');
INSERT INTO t1 (hex_cp) values('0613');
INSERT INTO t1 (hex_cp) values('0614');
INSERT INTO t1 (hex_cp) values('0615');
INSERT INTO t1 (hex_cp) values('0616');
INSERT INTO t1 (hex_cp) values('0617');
INSERT INTO t1 (hex_cp) values('0618');
INSERT INTO t1 (hex_cp) values('0619');
INSERT INTO t1 (hex_cp) values('061A');
INSERT INTO t1 (hex_cp) values('0640');
INSERT INTO t1 (hex_cp) values('06D6');
INSERT INTO t1 (hex_cp) values('06D7');
INSERT INTO t1 (hex_cp) values('06D8');
INSERT INTO t1 (hex_cp) values('06D9');
INSERT INTO t1 (hex_cp) values('06DA');
INSERT INTO t1 (hex_cp) values('06DB');
INSERT INTO t1 (hex_cp) values('06DC');
INSERT INTO t1 (hex_cp) values('06DD');
INSERT INTO t1 (hex_cp) values('06DF');
INSERT INTO t1 (hex_cp) values('06E0');
INSERT INTO t1 (hex_cp) values('06E1');
INSERT INTO t1 (hex_cp) values('06E2');
INSERT INTO t1 (hex_cp) values('06E3');
INSERT INTO t1 (hex_cp) values('06E4');
INSERT INTO t1 (hex_cp) values('06E7');
INSERT INTO t1 (hex_cp) values('06E8');
INSERT INTO t1 (hex_cp) values('06EA');
INSERT INTO t1 (hex_cp) values('06EB');
INSERT INTO t1 (hex_cp) values('06EC');
INSERT INTO t1 (hex_cp) values('06ED');
INSERT INTO t1 (hex_cp) values('070F');
INSERT INTO t1 (hex_cp) values('0740');
INSERT INTO t1 (hex_cp) values('0743');
INSERT INTO t1 (hex_cp) values('0744');
INSERT INTO t1 (hex_cp) values('0747');
INSERT INTO t1 (hex_cp) values('0748');
INSERT INTO t1 (hex_cp) values('0749');
INSERT INTO t1 (hex_cp) values('074A');
INSERT INTO t1 (hex_cp) values('07FA');
INSERT INTO t1 (hex_cp) values('0951');
INSERT INTO t1 (hex_cp) values('0952');
INSERT INTO t1 (hex_cp) values('0F18');
INSERT INTO t1 (hex_cp) values('0F19');
INSERT INTO t1 (hex_cp) values('0F35');
INSERT INTO t1 (hex_cp) values('0F37');
INSERT INTO t1 (hex_cp) values('0F82');
INSERT INTO t1 (hex_cp) values('0F83');
INSERT INTO t1 (hex_cp) values('0F86');
INSERT INTO t1 (hex_cp) values('0F87');
INSERT INTO t1 (hex_cp) values('0FC6');
INSERT INTO t1 (hex_cp) values('17D3');
INSERT INTO t1 (hex_cp) values('180A');
INSERT INTO t1 (hex_cp) values('180B');
INSERT INTO t1 (hex_cp) values('180C');
INSERT INTO t1 (hex_cp) values('180D');
INSERT INTO t1 (hex_cp) values('1A7F');
INSERT INTO t1 (hex_cp) values('1B6B');
INSERT INTO t1 (hex_cp) values('1B6C');
INSERT INTO t1 (hex_cp) values('1B6D');
INSERT INTO t1 (hex_cp) values('1B6E');
INSERT INTO t1 (hex_cp) values('1B6F');
INSERT INTO t1 (hex_cp) values('1B70');
INSERT INTO t1 (hex_cp) values('1B71');
INSERT INTO t1 (hex_cp) values('1B72');
INSERT INTO t1 (hex_cp) values('1B73');
INSERT INTO t1 (hex_cp) values('1CD0');
INSERT INTO t1 (hex_cp) values('1CD1');
INSERT INTO t1 (hex_cp) values('1CD2');
INSERT INTO t1 (hex_cp) values('1CD3');
INSERT INTO t1 (hex_cp) values('1CD4');
INSERT INTO t1 (hex_cp) values('1CD5');
INSERT INTO t1 (hex_cp) values('1CD6');
INSERT INTO t1 (hex_cp) values('1CD7');
INSERT INTO t1 (hex_cp) values('1CD8');
INSERT INTO t1 (hex_cp) values('1CD9');
INSERT INTO t1 (hex_cp) values('1CDA');
INSERT INTO t1 (hex_cp) values('1CDB');
INSERT INTO t1 (hex_cp) values('1CDC');
INSERT INTO t1 (hex_cp) values('1CDD');
INSERT INTO t1 (hex_cp) values('1CDE');
INSERT INTO t1 (hex_cp) values('1CDF');
INSERT INTO t1 (hex_cp) values('1CE0');
INSERT INTO t1 (hex_cp) values('1CE1');
INSERT INTO t1 (hex_cp) values('1CE2');
INSERT INTO t1 (hex_cp) values('1CE3');
INSERT INTO t1 (hex_cp) values('1CE4');
INSERT INTO t1 (hex_cp) values('1CE5');
INSERT INTO t1 (hex_cp) values('1CE6');
INSERT INTO t1 (hex_cp) values('1CE7');
INSERT INTO t1 (hex_cp) values('1CE8');
INSERT INTO t1 (hex_cp) values('200B');
INSERT INTO t1 (hex_cp) values('200C');
INSERT INTO t1 (hex_cp) values('200D');
INSERT INTO t1 (hex_cp) values('200E');
INSERT INTO t1 (hex_cp) values('200F');
INSERT INTO t1 (hex_cp) values('202A');
INSERT INTO t1 (hex_cp) values('202B');
INSERT INTO t1 (hex_cp) values('202C');
INSERT INTO t1 (hex_cp) values('202D');
INSERT INTO t1 (hex_cp) values('202E');
INSERT INTO t1 (hex_cp) values('2060');
INSERT INTO t1 (hex_cp) values('2061');
INSERT INTO t1 (hex_cp) values('2062');
INSERT INTO t1 (hex_cp) values('2063');
INSERT INTO t1 (hex_cp) values('2064');
INSERT INTO t1 (hex_cp) values('206A');
INSERT INTO t1 (hex_cp) values('206B');
INSERT INTO t1 (hex_cp) values('206C');
INSERT INTO t1 (hex_cp) values('206D');
INSERT INTO t1 (hex_cp) values('206E');
INSERT INTO t1 (hex_cp) values('206F');
INSERT INTO t1 (hex_cp) values('2D7F');
INSERT INTO t1 (hex_cp) values('A670');
INSERT INTO t1 (hex_cp) values('A671');
INSERT INTO t1 (hex_cp) values('A672');
INSERT INTO t1 (hex_cp) values('A8E0');
INSERT INTO t1 (hex_cp) values('A8E1');
INSERT INTO t1 (hex_cp) values('A8E2');
INSERT INTO t1 (hex_cp) values('A8E3');
INSERT INTO t1 (hex_cp) values('A8E4');
INSERT INTO t1 (hex_cp) values('A8E5');
INSERT INTO t1 (hex_cp) values('A8E6');
INSERT INTO t1 (hex_cp) values('A8E7');
INSERT INTO t1 (hex_cp) values('A8E8');
INSERT INTO t1 (hex_cp) values('A8E9');
INSERT INTO t1 (hex_cp) values('A8EA');
INSERT INTO t1 (hex_cp) values('A8EB');
INSERT INTO t1 (hex_cp) values('A8EC');
INSERT INTO t1 (hex_cp) values('A8ED');
INSERT INTO t1 (hex_cp) values('A8EE');
INSERT INTO t1 (hex_cp) values('A8EF');
INSERT INTO t1 (hex_cp) values('A8F0');
INSERT INTO t1 (hex_cp) values('A8F1');
INSERT INTO t1 (hex_cp) values('FE00');
INSERT INTO t1 (hex_cp) values('FE01');
INSERT INTO t1 (hex_cp) values('FE02');
INSERT INTO t1 (hex_cp) values('FE03');
INSERT INTO t1 (hex_cp) values('FE04');
INSERT INTO t1 (hex_cp) values('FE05');
INSERT INTO t1 (hex_cp) values('FE06');
INSERT INTO t1 (hex_cp) values('FE07');
INSERT INTO t1 (hex_cp) values('FE08');
INSERT INTO t1 (hex_cp) values('FE09');
INSERT INTO t1 (hex_cp) values('FE0A');
INSERT INTO t1 (hex_cp) values('FE0B');
INSERT INTO t1 (hex_cp) values('FE0C');
INSERT INTO t1 (hex_cp) values('FE0D');
INSERT INTO t1 (hex_cp) values('FE0E');
INSERT INTO t1 (hex_cp) values('FE0F');
INSERT INTO t1 (hex_cp) values('FE21');
INSERT INTO t1 (hex_cp) values('FE23');
INSERT INTO t1 (hex_cp) values('FE24');
INSERT INTO t1 (hex_cp) values('FE25');
INSERT INTO t1 (hex_cp) values('FE26');
INSERT INTO t1 (hex_cp) values('FE73');
INSERT INTO t1 (hex_cp) values('FEFF');
INSERT INTO t1 (hex_cp) values('FFF9');
INSERT INTO t1 (hex_cp) values('FFFA');
INSERT INTO t1 (hex_cp) values('FFFB');

-- convert Unicode hex to Unicode number
update t1 set unicode_cp = conv (hex_cp, 16, 10);

-- convert a Unicode codepoint to a UTF-8 number encoding
update t1 set utf8_enc = case when unicode_cp < 128 then unicode_cp when  unicode_cp < 2048 then (((unicode_cp >> 6) | 192) * 256 + (unicode_cp & 63) | 128) when unicode_cp < 65536 then (((unicode_cp >> 12) | 224) * 65536 + (((unicode_cp >> 6) & 63) | 128) * 256 + (unicode_cp & 63) | 128) end;
update t1 set s1=concat(_utf8'abc', chr (utf8_enc using utf8));

-- collations with level 3 or less: all INSERTED codepoints have zero weights, filter condition is STRCMP != 0 (no results should be returned)
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_de_exp, _utf8'abc') from t1 where strcmp(s1 collate utf8_de_exp, _utf8'abc') != 0 order by 1;
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_de_exp_ai_ci, _utf8'abc') from t1 where strcmp(s1 collate utf8_de_exp_ai_ci, _utf8'abc') != 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_gen_ai_ci, _utf8'abc') from t1 where strcmp(s1 collate utf8_gen_ai_ci, _utf8'abc') != 0 order by 1;
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_gen_ci, _utf8'abc') from t1 where strcmp(s1 collate utf8_gen_ci, _utf8'abc') != 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_fr_exp_ab, _utf8'abc') from t1 where strcmp(s1 collate utf8_fr_exp_ab, _utf8'abc') != 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_ja_exp, _utf8'abc') from t1 where strcmp(s1 collate utf8_ja_exp, _utf8'abc') != 0 order by 1;
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_ja_exp_cbm, _utf8'abc') from t1 where strcmp(s1 collate utf8_ja_exp_cbm, _utf8'abc') != 0 order by 1;


-- collations with level 4 (or equivalent): only a few characters have zero weight, filter condition is STRCMP == 0
-- built-in
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_bin, _utf8'abc') from t1 where strcmp(s1 collate utf8_bin, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_en_cs, _utf8'abc') from t1 where strcmp(s1 collate utf8_en_cs, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_en_ci, _utf8'abc') from t1 where strcmp(s1 collate utf8_en_ci, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_tr_cs, _utf8'abc') from t1 where strcmp(s1 collate utf8_tr_cs, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_ko_cs, _utf8'abc') from t1 where strcmp(s1 collate utf8_ko_cs, _utf8'abc') = 0 order by 1;

-- LDML
select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_gen, _utf8'abc') from t1 where strcmp(s1 collate utf8_gen, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_es_cs, _utf8'abc') from t1 where strcmp(s1 collate utf8_es_cs, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_km_exp, _utf8'abc') from t1 where strcmp(s1 collate utf8_km_exp, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_ko_cs_uca, _utf8'abc') from t1 where strcmp(s1 collate utf8_ko_cs_uca, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_tr_cs_uca, _utf8'abc') from t1 where strcmp(s1 collate utf8_tr_cs_uca, _utf8'abc') = 0 order by 1;

select hex_cp, s1, hex(s1), strcmp(s1 collate utf8_vi_cs, _utf8'abc') from t1 where strcmp(s1 collate utf8_vi_cs, _utf8'abc') = 0 order by 1;

drop table t1;

SET NAMES iso88591;
commit;
--+ holdcas off;
