prepare stmt0 from 'select * from db_root';
drop prepare stmt0;
prepare stmt1 from 'select * from db_root';
drop prepare stmt1;
prepare stmt2 from 'select * from db_root';
drop prepare stmt2;
prepare stmt3 from 'select * from db_root';
drop prepare stmt3;
prepare stmt4 from 'select * from db_root';
drop prepare stmt4;
prepare stmt5 from 'select * from db_root';
drop prepare stmt5;
prepare stmt6 from 'select * from db_root';
drop prepare stmt6;
prepare stmt7 from 'select * from db_root';
drop prepare stmt7;
prepare stmt8 from 'select * from db_root';
drop prepare stmt8;
prepare stmt9 from 'select * from db_root';
drop prepare stmt9;
prepare stmt10 from 'select * from db_root';
drop prepare stmt10;
prepare stmt11 from 'select * from db_root';
drop prepare stmt11;
prepare stmt12 from 'select * from db_root';
drop prepare stmt12;
prepare stmt13 from 'select * from db_root';
drop prepare stmt13;
prepare stmt14 from 'select * from db_root';
drop prepare stmt14;
prepare stmt15 from 'select * from db_root';
drop prepare stmt15;
prepare stmt16 from 'select * from db_root';
drop prepare stmt16;
prepare stmt17 from 'select * from db_root';
drop prepare stmt17;
prepare stmt18 from 'select * from db_root';
drop prepare stmt18;
prepare stmt19 from 'select * from db_root';
drop prepare stmt19;
--test: below will fail and throw 'ERROR: No error message available'
prepare stmt20 from 'select * from db_root';
drop prepare stmt20;
