create table t(a int);
insert into t values(1);
insert into t values(10);
insert into t values(100);
create index idx on t(log10(a));
set optimization level 513;
select/*+ recompile*/ log10(a) from t where log10(a)>0 order by 1;
drop table t;
create table t(a int);
insert into t values(1);
insert into t values(10);
insert into t values(100);
create index idx on t(log10(a),a);
set optimization level 513;
select /*+ recompile*/ a,log10(a) from t where log10(a)>0 order by 1;
select /*+ recompile*/ log10(a),a from t where log10(a)>0 order by 1;
select /*+ recompile*/ a,log10(a) from t where log10(a)>0 order by 2,1;
select /*+ recompile*/ log10(a),a from t where log10(a)>0 order by 1,2;
drop table t;