autocommit off;
create class many_reps(a int, b int, c int);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
drop   index idx on many_reps (c);
create index idx on many_reps (c);
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
select count(*) from many_reps where c < 10;
select count(*) from many_reps where b < 10;
commit work;
drop class many_reps;
commit work;
