autocommit off;
create class many_reps(a int, b int, c int);
create index i_many_reps_c on many_reps (c);
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
alter class many_reps drop attribute a;
alter class many_reps add attribute a integer;
update statistics on many_reps;
insert into many_reps (a, b, c) values (1, 1, 1);
insert into many_reps (a, b, c) values (2, 2, 2);
commit work;
select count(*) from many_reps where c < 10;
select count(*) from many_reps where b < 10;
commit work;
drop class many_reps;
commit work;
