autocommit off;
create class foo (a int, b int);
insert into foo values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
alter foo add attribute c int;
insert into foo(a, b) values (1, 0);
alter foo drop attribute c;
insert into foo(a, b) values (1, 0);
select * from foo;
drop foo;
rollback;
