drop table if exists t1;
create table t1 (a int, b int,c int);
insert into t1 SET a=1, b=a+1;
insert into t1 SET a=b+1, b=1, c=b+2;
insert into t1 SET a=b+1, b=a+1, c=b+2;
select * from t1 order by 1;
drop t1;
create table t1 (a int, b int default 0,c int);
insert into t1 SET a=1, b=a+1;
insert into t1 SET a=b+1, b=1, c=b+2;
insert into t1 SET a=b+1, b=a+1, c=b+2;
select * from t1 order by 1;
drop t1;
create table t1 (a int, b int default 0,c int default 0);
insert into t1 SET a=1, b=a+1;
insert into t1 SET a=b+1, b=1, c=b+2;
insert into t1 SET a=b+1, b=a+1, c=b+2;
select * from t1 order by 1;
drop t1;
create table t1 (a int default 0, b int default 0,c int default 0);
insert into t1 SET a=1, b=a+1;
insert into t1 SET a=b+1, b=1, c=b+2;
insert into t1 SET a=b+1, b=a+1, c=b+2;
select * from t1 order by 1;
drop t1;