drop if exists t1;
CREATE TABLE T1(
Y INT, 
M INT, 
SALES INT 
);
WITH D AS (SELECT Y, SUM(SALES) AS S FROM T1 GROUP BY Y)
SELECT D1.Y, (CASE WHEN D1.S>D2.S THEN 'INCREASE' ELSE 'DECREASE' END) AS TREND
FROM
 D AS D1,
 D AS D2
WHERE D1.Y = D2.Y-1;
insert into t1 values(1988,12,3000);
insert into t1 values(1989,12,5000);
insert into t1 values(1990,12,1000);
WITH D AS (SELECT Y, SUM(SALES) AS S FROM T1 GROUP BY Y)
SELECT D1.Y, (CASE WHEN D1.S>D2.S THEN 'INCREASE' ELSE 'DECREASE' END) AS TREND
FROM
 D AS D1,
 D AS D2
 WHERE D1.Y = D2.Y-1;

WITH D AS (SELECT Y, SUM(SALES) AS S FROM T1 GROUP BY Y)
SELECT D1.Y, D2.Y AS TREND
FROM
 D AS D1,
 D AS D2
 WHERE D1.Y = D2.Y-1;
 WITH D AS (SELECT Y, SUM(SALES) AS S FROM T1 GROUP BY Y)
SELECT D1.Y, D2.Y,(CASE WHEN D1.S>D2.S THEN 'INCREASE' ELSE 'DECREASE' END) AS TREND
FROM
 D AS D1,
 D AS D2
 WHERE D1.Y = D2.Y-1;
 
  WITH D AS (SELECT Y, SUM(SALES) AS S FROM T1 GROUP BY Y)
SELECT D1.Y,(CASE WHEN D1.S>D2.S THEN 'INCREASE' ELSE 'DECREASE' END) AS TREND
FROM
 D AS D1,
 D AS D2
 WHERE D1.Y = D2.Y-1;
drop if exists t1;

