drop table if exists t;
create table t(a json);
insert into t values(json_object('addtime', '2017-12-12 14:17'));
insert into t values(json_object('addtime', '2017-12-11 11:17'));
insert into t values(json_object('addtime', '2017-12-14 1:17'));
select GREATEST(cast(json_extract(a, '/addtime') as datetime)) from t;
select LEAST(cast(json_extract(a, '/addtime') as datetime)) from t;
insert into t values(json_object('addtime', '03:05:32.952 PM 12/12/2017'));
insert into t values(json_object('addtime', '03:05:32 PM'));
delete from t where json_extract(a, '/addtime') not like '%PM%';
select LEAST(cast(json_extract(a, '/addtime') as string)) from t;  
select GREATEST(cast(json_extract(a, '/addtime') as string)) from t;  
drop table if exists t;
drop table if exists t9;
create table t9(a json, b datetime);
insert into t9 values(json_object('addtime', '03:25:47 PM'), '02:25:47 PM 11/12/2017');
insert into t9 values(json_object('addtime', '03:25:47.161 PM 12/12/2017 '), '03:25:47.161 PM 11/12/2017 '); 
select GREATEST(json_extract(a, '/addtime'), b) from t9;
select GREATEST(cast(json_extract(a, '/addtime') as string)) from t9;
select GREATEST(cast(json_extract(a, '/addtime') as string), b) from t9;
select GREATEST(cast(json_extract(a, '/addtime') as string), cast(b as string)) from t9;
select LEAST(cast(json_extract(a, '/addtime') as string), cast(b as string)) from t9;
select GREATEST('10:44:34.874 AM 12/12/2017', cast(json_extract(a, '/add') as string)) from t9;
select LEAST('10:44:34.874 AM 12/12/2017', cast(json_extract(a, '/add') as string)) from t9;
select GREATEST('10:44:34.874 AM 12/12/2017', cast(json_extract('{"addby":"cubrid"}', '/addby')as string)) from t9;
select LEAST('10:44:34.874 AM 12/12/2017', cast(json_extract('{"addby":"cubrid"}', '/addby')as string)) from t9;
select GREATEST(json_extract(json_array(1, 2, 123), '/0'), json_extract(json_array(1, 2, 123), '/2'));
select LEAST(json_extract(json_array(1, 2, 123), '/0'), json_extract(json_array(1, 2, 123), '/2'));
delete from t9 where rownum > cast(json_extract('{"rownum":"-1"}', '/rownum') as integer);
insert into t9 values(json_object('addtime', to_char(sys_time)), sys_datetime+1);
insert into t9 values(json_object('addtime', to_char(sys_datetime + 22)), sys_datetime); 
select count(*) from t9;
drop table if exists t9;
