autocommit off;
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         250,          250, 'QJ', 'QJ', 
                          0,            0,            2,            2,       
                          0,            0,            0,            0,       
                          0,            0, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         251,          251, 'RJ', 'RJ', 
                          1,            1,            3,            3,       
                          1,            1,            1,            1,       
                          1,            1, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         252,          252, 'SJ', 'SJ', 
                          0,            0,            0,            0,       
                          2,            2,            2,            2,       
                          2,            2, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         253,          253, 'TJ', 'TJ', 
                          1,            1,            1,            1,       
                          3,            3,            3,            3,       
                          3,            3, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         254,          254, 'UJ', 'UJ', 
                          0,            0,            2,            2,       
                          4,            4,            4,            4,       
                          4,            4, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         255,          255, 'VJ', 'VJ', 
                          1,            1,            3,            3,       
                          0,            0,            5,            5,       
                          5,            5, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         256,          256, 'WJ', 'WJ', 
                          0,            0,            0,            0,       
                          1,            1,            6,            6,       
                          6,            6, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         257,          257, 'XJ', 'XJ', 
                          1,            1,            1,            1,       
                          2,            2,            7,            7,       
                          7,            7, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         258,          258, 'YJ', 'YJ', 
                          0,            0,            2,            2,       
                          3,            3,            8,            8,       
                          8,            8, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         259,          259, 'ZJ', 'ZJ', 
                          1,            1,            3,            3,       
                          4,            4,            9,            9,       
                          9,            9, '@');
SELECT COUNT(*) FROM base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
ROLLBACK WORK;
SELECT COUNT(*) FROM base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
