autocommit off;
SET TRANSACTION ISOLATION LEVEL
    REPEATABLE READ CLASS, READ COMMITTED INSTANCES;
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         310,          310, 'YL', 'YL', 
                          0,            0,            2,            2,       
                          0,            0,            0,            0,       
                         10,           10, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         311,          311, 'ZL', 'ZL', 
                          1,            1,            3,            3,       
                          1,            1,            1,            1,       
                         11,           11, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         312,          312, 'AM', 'AM', 
                          0,            0,            0,            0,       
                          2,            2,            2,            2,       
                         12,           12, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         313,          313, 'BM', 'BM', 
                          1,            1,            1,            1,       
                          3,            3,            3,            3,       
                         13,           13, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         314,          314, 'CM', 'CM', 
                          0,            0,            2,            2,       
                          4,            4,            4,            4,       
                         14,           14, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         315,          315, 'DM', 'DM', 
                          1,            1,            3,            3,       
                          0,            0,            5,            5,       
                         15,           15, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         316,          316, 'EM', 'EM', 
                          0,            0,            0,            0,       
                          1,            1,            6,            6,       
                         16,           16, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         317,          317, 'FM', 'FM', 
                          1,            1,            1,            1,       
                          2,            2,            7,            7,       
                         17,           17, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         318,          318, 'GM', 'GM', 
                          0,            0,            2,            2,       
                          3,            3,            8,            8,       
                         18,           18, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         319,          319, 'HM', 'HM', 
                          1,            1,            3,            3,       
                          4,            4,            9,            9,       
                         19,           19, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         320,          320, 'IM', 'IM', 
                          0,            0,            0,            0,       
                          0,            0,            0,            0,       
                         20,           20, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         321,          321, 'JM', 'JM', 
                          1,            1,            1,            1,       
                          1,            1,            1,            1,       
                         21,           21, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         322,          322, 'KM', 'KM', 
                          0,            0,            2,            2,       
                          2,            2,            2,            2,       
                         22,           22, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         323,          323, 'LM', 'LM', 
                          1,            1,            3,            3,       
                          3,            3,            3,            3,       
                         23,           23, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         324,          324, 'MM', 'MM', 
                          0,            0,            0,            0,       
                          4,            4,            4,            4,       
                         24,           24, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         325,          325, 'NM', 'NM', 
                          1,            1,            1,            1,       
                          0,            0,            5,            5,       
                         25,           25, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         326,          326, 'OM', 'OM', 
                          0,            0,            2,            2,       
                          1,            1,            6,            6,       
                         26,           26, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         327,          327, 'PM', 'PM', 
                          1,            1,            3,            3,       
                          2,            2,            7,            7,       
                         27,           27, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         328,          328, 'QM', 'QM', 
                          0,            0,            0,            0,       
                          3,            3,            8,            8,       
                         28,           28, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         329,          329, 'RM', 'RM', 
                          1,            1,            1,            1,       
                          4,            4,            9,            9,       
                         29,           29, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         330,          330, 'SM', 'SM', 
                          0,            0,            2,            2,       
                          0,            0,            0,            0,       
                         30,           30, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         331,          331, 'TM', 'TM', 
                          1,            1,            3,            3,       
                          1,            1,            1,            1,       
                         31,           31, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         332,          332, 'UM', 'UM', 
                          0,            0,            0,            0,       
                          2,            2,            2,            2,       
                         32,           32, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         333,          333, 'VM', 'VM', 
                          1,            1,            1,            1,       
                          3,            3,            3,            3,       
                         33,           33, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         334,          334, 'WM', 'WM', 
                          0,            0,            2,            2,       
                          4,            4,            4,            4,       
                         34,           34, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         335,          335, 'XM', 'XM', 
                          1,            1,            3,            3,       
                          0,            0,            5,            5,       
                         35,           35, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         336,          336, 'YM', 'YM', 
                          0,            0,            0,            0,       
                          1,            1,            6,            6,       
                         36,           36, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         337,          337, 'ZM', 'ZM', 
                          1,            1,            1,            1,       
                          2,            2,            7,            7,       
                         37,           37, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         338,          338, 'AN', 'AN', 
                          0,            0,            2,            2,       
                          3,            3,            8,            8,       
                         38,           38, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         339,          339, 'BN', 'BN', 
                          1,            1,            3,            3,       
                          4,            4,            9,            9,       
                         39,           39, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         340,          340, 'CN', 'CN', 
                          0,            0,            0,            0,       
                          0,            0,            0,            0,       
                         40,           40, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         341,          341, 'DN', 'DN', 
                          1,            1,            1,            1,       
                          1,            1,            1,            1,       
                         41,           41, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         342,          342, 'EN', 'EN', 
                          0,            0,            2,            2,       
                          2,            2,            2,            2,       
                         42,           42, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         343,          343, 'FN', 'FN', 
                          1,            1,            3,            3,       
                          3,            3,            3,            3,       
                         43,           43, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         344,          344, 'GN', 'GN', 
                          0,            0,            0,            0,       
                          4,            4,            4,            4,       
                         44,           44, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         345,          345, 'HN', 'HN', 
                          1,            1,            1,            1,       
                          0,            0,            5,            5,       
                         45,           45, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         346,          346, 'IN', 'IN', 
                          0,            0,            2,            2,       
                          1,            1,            6,            6,       
                         46,           46, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         347,          347, 'JN', 'JN', 
                          1,            1,            3,            3,       
                          2,            2,            7,            7,       
                         47,           47, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         348,          348, 'KN', 'KN', 
                          0,            0,            0,            0,       
                          3,            3,            8,            8,       
                         48,           48, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         349,          349, 'LN', 'LN', 
                          1,            1,            1,            1,       
                          4,            4,            9,            9,       
                         49,           49, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         350,          350, 'MN', 'MN', 
                          0,            0,            2,            2,       
                          0,            0,            0,            0,       
                          0,            0, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         351,          351, 'NN', 'NN', 
                          1,            1,            3,            3,       
                          1,            1,            1,            1,       
                          1,            1, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         352,          352, 'ON', 'ON', 
                          0,            0,            0,            0,       
                          2,            2,            2,            2,       
                          2,            2, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         353,          353, 'PN', 'PN', 
                          1,            1,            1,            1,       
                          3,            3,            3,            3,       
                          3,            3, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         354,          354, 'QN', 'QN', 
                          0,            0,            2,            2,       
                          4,            4,            4,            4,       
                          4,            4, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         355,          355, 'RN', 'RN', 
                          1,            1,            3,            3,       
                          0,            0,            5,            5,       
                          5,            5, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         356,          356, 'SN', 'SN', 
                          0,            0,            0,            0,       
                          1,            1,            6,            6,       
                          6,            6, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         357,          357, 'TN', 'TN', 
                          1,            1,            1,            1,       
                          2,            2,            7,            7,       
                          7,            7, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         358,          358, 'UN', 'UN', 
                          0,            0,            2,            2,       
                          3,            3,            8,            8,       
                          8,            8, '@');
INSERT INTO base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (         359,          359, 'VN', 'VN', 
                          1,            1,            3,            3,       
                          4,            4,            9,            9,       
                          9,            9, '@');
ROLLBACK WORK;
SELECT COUNT(*) FROM base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
