drop if exists t;
create table t(i int primary key, name varchar(20),job varchar(20));
insert into t values(1,'Jone','teacher');
insert into t values(2,'Chandel','programmer');
insert into t values(3,'Jim',null);
insert into t select rownum+3,'person'||rownum,'unkown' from db_root connect by level <=10;
create index idx_t_job on t(job);
select * from t where job='unkown' using index pk_t_i limit 3-1+(10/2)-(1*5)  offset 0+3+(5/5);
select * from t where job='unkown' using index pk_t_i order by 1  limit 3-1 offset 0+3-0+2/2-1 ;
drop if exists t;
