drop if exists t1;
CREATE TABLE t1 (id INT PRIMARY KEY, a INT, b INT, c INT);
CREATE INDEX i_t1_ac ON t1(a,c);
INSERT INTO t1 values(1,1,1,1);
INSERT INTO t1 values(2,2,1,1);
INSERT INTO t1 values(3,3,1,1);
INSERT INTO t1 values(4,4,1,1);
INSERT INTO t1 values(5,5,1,1);
INSERT INTO t1 values(6,6,1,1);
delete from t1 where a<6 and a>1 using index i_t1_ac keylimit 1;
delete from t1 where a<6 and a>1 using index i_t1_ac keylimit 1,2;
select * from t1 order by 1;
INSERT INTO t1 values(2,2,1,1);
INSERT INTO t1 values(4,4,1,1);
INSERT INTO t1 values(5,5,1,1);
update t1 set b=a where a<6 and a>1 using index i_t1_ac keylimit 1;
update t1 set b=a where a<6 and a>1 using index i_t1_ac keylimit 2,5;
select * from t1 order by 1;
drop if exists t1;
CREATE TABLE t1 (id INT PRIMARY KEY, a INT, b INT, c INT);
CREATE INDEX i_t1_ac ON t1(a,c);
INSERT INTO t1 select rownum,rownum,1,1 from db_root connect by level<=100;
delete from t1 where a<6  using index i_t1_ac keylimit 0+3;
delete from t1 where a<6  using index i_t1_ac keylimit 0+8;
delete from t1 where a<12 using index i_t1_ac keylimit 1+1,2;
delete from t1 where a<18  using index i_t1_ac keylimit 0+3,4*2/1*2;
select * from t1 order by 1 limit 10;
update t1 set c=a where a<24 using index i_t1_ac keylimit 1,1;
update t1 set b=a where a<30 using index i_t1_ac keylimit 1+1,5*1*2;
select * from t1 order by 1 limit 30;
drop if exists t1;
