CREATE TABLE a (col INTEGER);
CREATE TABLE b (col INTEGER);
create table c (col1 int, col2 int);
INSERT INTO a VALUES (1);
INSERT INTO a VALUES (2);
INSERT INTO a VALUES (3);
INSERT INTO a VALUES (4);
INSERT INTO b VALUES (2);
INSERT INTO b VALUES (3);
INSERT INTO b VALUES (4);
INSERT INTO b VALUES (5);

SELECT col FROM b WHERE col NOT IN (SELECT col FROM a);
SELECT col FROM b WHERE col NOT IN (SELECT * FROM a);

SELECT col FROM b WHERE col NOT IN (SELECT col1 FROM c) order by 1;

drop table a, b, c;
