/* 2. CREATE Float NUMERIC (default NUMERIC) */

evaluate '1. CREATE Float NUMERIC: SHOW CREATE TABLE output';
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (col1 NUMERIC);
SHOW CREATE TABLE t1;
DROP TABLE IF EXISTS t1;
