--TEST: large number of substrings in the string list on client side


--TEST: client side
select find_in_set('a', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('a', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 1, 'ok', 'nok');

--TEST: client side
select find_in_set('uv', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('uv', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 37, 'ok', 'nok');

--TEST: client side
select find_in_set('pqrs', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('pqrs', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 61, 'ok', 'nok');

--TEST: client side
select find_in_set('zab', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('zab', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 83, 'ok', 'nok');

--TEST: client side
select find_in_set('uvwxy', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('uvwxy', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 96, 'ok', 'nok');

--TEST: client side
select find_in_set('yza', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('yza', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 48, 'ok', 'nok');

--TEST: client side
select find_in_set('wxyza', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza') result, if(find_in_set('wxyza', 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh,ij,kl,mn,op,qr,st,uv,wx,yz,abc,def,ghi,jkl,mno,pqr,stu,vwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabc,defg,hijk,lmno,pqrs,tuvw,xyza,bcde,fghi,jklm,nopq,rstu,vwxy,za,bc,de,fg,hi,jk,lm,no,pq,rs,tu,vw,xy,zab,cde,fgh,ijk,lmn,opq,rst,uvw,xyz,abcde,fghij,klmno,pqrst,uvwxy,zabcd,efghi,jklmn,opqrs,tuvwx,yza,bcd,efg,hij,klm,nop,qrs,tuv,wxy,zabcd,efghi,jklmn,opqrs,tuvwx,yzabc,defgh,ijklm,nopqr,stuvw,xyzab,cdefg,hijkl,mnopq,rstuv,wxyza')  = 126, 'ok', 'nok');



--TEST: long string to the 1st param
select find_in_set('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'a,b,c,d,eeeeeeeeee,ffffffffffffffffffffffffffff,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,gggggggggg,kkk') result, if(find_in_set('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'a,b,c,d,eeeeeeeeee,ffffffffffffffffffffffffffff,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,gggggggggg,kkk')  = 7, 'ok', 'nok');

