drop table if exists tb1;

create table tb1(peopleid int) partition by range(peopleid)(partition old values less than (50),partition middle values less than (100),partition new values less than (200),partition large values less than maxvalue);
insert into tb1 values(-13),(50),(100),(200),(1024);
select * from tb1__p__new order by peopleid;
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__large order by peopleid;
alter table tb1 reorganize partition large into (partition large values less than (1024),partition large2 values less than maxvalue);
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__new order by peopleid;
select * from tb1__p__large order by peopleid;
select * from tb1__p__large2 order by peopleid;
insert into tb1 values(1023),(1025);
select * from tb1__p__new order by peopleid;
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__large order by peopleid;
select * from tb1__p__large2 order by peopleid;
alter table tb1 reorganize partition new,large into (partition new2 values less than (1024));
select * from tb1__p__new order by peopleid;
select * from tb1__p__new2 order by peopleid;
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__large order by peopleid;
select * from tb1__p__large2 order by peopleid;
insert into tb1 values(200),(1024);
select * from tb1__p__new2 order by peopleid;
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__large2 order by peopleid;
alter table tb1 reorganize partition middle,new2 into (partition middle2 values less than (1023));
alter table tb1 reorganize partition middle,new2 into (partition middle2 values less than (1025));
alter table tb1 reorganize partition middle,new2 into (partition middle2 values less than (1024));
insert into tb1 values(1025),(101),(NULL);
select * from tb1__p__new2 order by peopleid;
select * from tb1__p__old order by peopleid;
select * from tb1__p__middle order by peopleid;
select * from tb1__p__middle2 order by peopleid;
select * from tb1__p__large2 order by peopleid;
alter table tb1 reorganize partition old,large2 into (partition old2 values less than maxvalue);
select * from tb1__p__middle2 order by peopleid;
select * from tb1__p__old2 order by peopleid;
select * from tb1__p__old order by peopleid;
insert into tb1 values(49),(50),(2147483647),(-2147483648),(NULL);
select * from tb1__p__middle2 order by peopleid;
select * from tb1__p__old2 order by peopleid;
alter table tb1 reorganize partition middle2 into (partition middle3 values less than (-0),partition middle4 values less than (1000),partition middle5 values less than (1024));
alter table tb1 reorganize partition middle3,middle4 into (partition middle34 values less than (1002));
alter table tb1 reorganize partition middle3,middle4,middle5 into (partition middle11 values less than (1002),partition middle22 values less than (1024));
insert into tb1 values (0),(1001),(1002),(1024);
select * from tb1__p__middle11 order by peopleid;
select * from tb1__p__middle22 order by peopleid;
select * from tb1__p__old2 order by peopleid;
drop table tb1;

