-- Syntax
-- Syntax/ Metrics/ Valid
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', COSINE);
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', MANHATTAN);
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', DOT);
-- Not Implemented/ SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', JACCARD);
-- Not Implemented/ SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', HAMMING);
-- Syntax/ Metrics/ Error
-- SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', some_random_token); -- breaks CTP
-- SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', SOME_RANDOM_TOKEN); -- breaks CTP
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', VECTOR_DISTANCE);

-- Semantics
-- Semantics/ Error
SELECT VECTOR_DISTANCE();
SELECT VECTOR_DISTANCE('[1,2,3]');
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]');
-- Semantics/ No Metrics/ Error
-- SELECT VECTOR_DISTANCE(NULL, NULL);
-- SELECT VECTOR_DISTANCE(NULL, '[3,2,1]');
-- SELECT VECTOR_DISTANCE('[1,2,3]', NULL);
-- Semantics/ Wrong Metrics/ Error
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', '[1,2,3]');
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]');
-- SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1]', 99);
-- Semantics/ Wrong Argument Types/ Error
SELECT VECTOR_DISTANCE(1, '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,2,3]', 1, EUCLIDEAN);
-- Semantics/ Wrong Argument Formats/ Error
SELECT VECTOR_DISTANCE('', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE(']', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE(',', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[,', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE(',]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[,]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1,', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1,]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,2,3', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1,2,3]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('1,2,3', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '', [EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', ']', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[1', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', ',', [EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[,', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', ',]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[,]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1,', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[1,', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1,]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[1,]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '[1,2,3', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1,2,3]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[3,2,1]', '1,2,3', EUCLIDEAN);
SELECT VECTOR_DISTANCE('hello world', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[hello world', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('hello world]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[hello,world]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,2,3]', '[hello,world]', EUCLIDEAN);

-- Spec/ Not Equal Dimensions/ Error
SELECT VECTOR_DISTANCE('[1,2,3,4]', '[3,2,1]', EUCLIDEAN);
SELECT VECTOR_DISTANCE('[1,2,3]', '[3,2,1,4]', EUCLIDEAN);

-- Spec/ Null Arguments/ Valid
-- Spec/ Null Arguments/ COSINE/ Valid
-- SELECT VECTOR_DISTANCE(NULL, NULL, COSINE);
-- SELECT VECTOR_DISTANCE(NULL, '[3,2,1]', COSINE);
-- SELECT VECTOR_DISTANCE('[1,2,3]', NULL, COSINE);
-- Spec/ Null Arguments/ EUCLIDEAN/ Valid
-- SELECT VECTOR_DISTANCE(NULL, NULL, EUCLIDEAN);
-- SELECT VECTOR_DISTANCE(NULL, '[3,2,1]', EUCLIDEAN);
-- SELECT VECTOR_DISTANCE('[1,2,3]', NULL, EUCLIDEAN);
