CREATE OR REPLACE FUNCTION test1() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testblob() RETURN java.lang.String';
CREATE OR REPLACE FUNCTION test2() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testblob1() RETURN java.lang.String';
CREATE OR REPLACE FUNCTION test3() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testblob2() RETURN java.lang.String';
CREATE OR REPLACE FUNCTION test4() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testclob() RETURN java.lang.String';
CREATE OR REPLACE FUNCTION test5() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testclob1() RETURN java.lang.String';
CREATE OR REPLACE FUNCTION test6() RETURN STRING AS LANGUAGE JAVA NAME 'SpTest9.testclob2() RETURN java.lang.String';

CALL test1();
CALL test2();
CALL test3();
CALL test4();
CALL test5();
CALL test6();

DROP FUNCTION test1;
DROP FUNCTION test2;
DROP FUNCTION test3;
DROP FUNCTION test4;
DROP FUNCTION test5;
DROP FUNCTION test6;
