--LAST_INSERT_ID FUNCTION
CREATE TABLE loo(a int PRIMARY KEY AUTO_INCREMENT, b char(10));

INSERT INTO loo(b) VALUES('AAA');
INSERT INTO loo(b) VALUES('BBB');
INSERT INTO loo(b) VALUES('CCC');
INSERT INTO loo(b) VALUES('DDD');
INSERT INTO loo(b) VALUES('EEE');

SELECT LAST_INSERT_ID();

INSERT INTO loo(b) VALUES ('FFF'), ('GGG'), ('HHH');

SELECT LAST_INSERT_ID();

DROP TABLE loo;

