--SHOW CREATE VIEW

CREATE TABLE t (qty INT, price INT);
INSERT INTO t VALUES(3, 50);

CREATE VIEW v AS SELECT qty, price, qty*price AS "value" FROM t;
SELECT * FROM v;
SHOW CREATE VIEW v;

DROP VIEW v;
DROP TABLE t;

