/* Ticket08 R14. Ported schema report; exact row and catalog model authored before runtime. SQL logical evidence only; private physical companion separately observes placement. Hard-default parameter restored to configured no. */

drop table if exists oos08_schema;
drop table if exists oos08_grow;
create table oos08_schema (id int primary key,a bit varying,b bit varying,note varchar(20),keep_col int);
insert into oos08_schema values(1,cast(repeat('a1',5000) as bit varying),cast(repeat('b2',4600) as bit varying),'base',10);
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='base' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema change b b bit varying first;
alter table oos08_schema change a a bit varying after note;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='base' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
select attr_name,def_order from db_attribute where class_name='oos08_schema' order by def_order;
alter table oos08_schema add meta_only varchar(20) after id;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='base' and keep_col=10 and meta_only is null then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema drop meta_only;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='base' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema add rewrite_data bit varying after b;
update oos08_schema set rewrite_data=cast(repeat('c3',1200) as bit varying),note='rewrite' where id=1;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='rewrite' and keep_col=10 and rewrite_data=cast(repeat('c3',1200) as bit varying) then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema drop rewrite_data;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='rewrite' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema modify a bit varying(50000) not null;
alter table oos08_schema modify note varchar(40);
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='rewrite' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
select attr_name,prec,is_nullable from db_attribute where class_name='oos08_schema' and attr_name in ('a','note') order by attr_name;
alter table oos08_schema modify a int storage default;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='rewrite' and keep_col=10 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
select count(*) as schema_ok from db_attribute where class_name='oos08_schema' and attr_name='a' and prec=50000 and is_nullable='NO' and data_type='VARBIT';
set system parameters 'add_column_update_hard_default=yes';
alter table oos08_schema add default_col int not null default 77 after keep_col;
select count(*) as n, min(case when id=1 and a=cast(repeat('a1',5000) as bit varying) and b=cast(repeat('b2',4600) as bit varying) and note='rewrite' and keep_col=10 and default_col=77 then 1 else 0 end) as exact_ok, min(md5(a)) as a_md5, min(md5(b)) as b_md5 from oos08_schema;
alter table oos08_schema drop b;
select count(*) as n,min(case when a=cast(repeat('a1',5000) as bit varying) and note='rewrite' and keep_col=10 and default_col=77 then 1 else 0 end) as exact_ok,min(md5(a)) as a_md5 from oos08_schema;
select count(*) as dropped_attribute from db_attribute where class_name='oos08_schema' and attr_name='b';
create table oos08_grow(id int primary key,a bit varying);
insert into oos08_grow values(1,cast(repeat('d4',3000) as bit varying));
select count(*) as n,min(case when a=cast(repeat('d4',3000) as bit varying) then 1 else 0 end) as exact_ok from oos08_grow;
alter table oos08_grow add grow_data bit varying not null default cast(repeat('e5',2500) as bit varying);
select count(*) as n,min(case when a=cast(repeat('d4',3000) as bit varying) and grow_data=cast(repeat('e5',2500) as bit varying) then 1 else 0 end) as exact_ok,min(md5(a)) as a_md5,min(md5(grow_data)) as grow_md5 from oos08_grow;
set system parameters 'add_column_update_hard_default=no';
drop table oos08_grow;
drop table oos08_schema;
