-- Ticket08 R06 accepted DEFAULT/PREFER_INLINE/FORCE_OUTLINE matrix. Fixed BIT is fixed; CHAR is eligible. Explicit unsupported-domain errors bind ER_PT_SEMANTIC=-494 to pinned source. FORCE_INLINE/fixed DEFAULT exceptions are proposals. Policy metadata and placement are independently asserted in shell.

drop table if exists oos08_policy;
drop table if exists oos08_like;
drop table if exists oos08_fixed;
drop table if exists oos08_char;
drop table if exists oos08_bad;
create table oos08_policy(id int primary key,a bit varying storage prefer_inline,b bit varying storage force_outline,c bit varying storage default);
insert into oos08_policy values(1,cast(repeat('a1',3500) as bit varying),cast(repeat('b2',300) as bit varying),cast(repeat('c3',2500) as bit varying));
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
create table oos08_like like oos08_policy;
insert into oos08_like select * from oos08_policy;
select count(*) as exact_copy from oos08_like x,oos08_policy y where x.id=y.id and x.a=y.a and x.b=y.b and x.c=y.c;
alter table oos08_policy modify a bit varying(60000);
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
alter table oos08_policy change b b bit varying(60000);
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
alter table oos08_policy modify a bit varying storage force_outline;
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
alter table oos08_policy change b b bit varying storage prefer_inline;
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
alter table oos08_policy modify a bit varying storage default;
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
alter table oos08_policy change b b bit varying storage prefer_outline;
select count(*) as n,min(case when id=1 and a=cast(repeat('a1',3500) as bit varying) and b=cast(repeat('b2',300) as bit varying) and c=cast(repeat('c3',2500) as bit varying) then 1 else 0 end) as exact_ok from oos08_policy;
create table oos08_fixed(c varchar(4) storage force_outline);
insert into oos08_fixed values('1234');
alter table oos08_fixed modify c int storage default;
select count(*) as exact_before from oos08_fixed where c='1234';
alter table oos08_fixed modify c int;
select c from oos08_fixed;
create table oos08_char(c char(32) storage prefer_inline);
insert into oos08_char values('variable-char');
select count(*) as exact_char from oos08_char where trim(c)='variable-char';
create table oos08_bad(c int storage default);
create table oos08_bad(c bit(128) storage default);
create table oos08_bad(c varchar(100) shared 'x' storage default);
create table oos08_bad class attribute(c varchar(100) storage default);
create vclass oos08_bad(c varchar(100) storage default);
create table oos08_bad(c int storage prefer_inline);
create table oos08_bad(c bit(128) storage prefer_inline);
create table oos08_bad(c varchar(100) shared 'x' storage prefer_inline);
create table oos08_bad class attribute(c varchar(100) storage prefer_inline);
create vclass oos08_bad(c varchar(100) storage prefer_inline);
create table oos08_bad(c int storage force_outline);
create table oos08_bad(c bit(128) storage force_outline);
create table oos08_bad(c varchar(100) shared 'x' storage force_outline);
create table oos08_bad class attribute(c varchar(100) storage force_outline);
create vclass oos08_bad(c varchar(100) storage force_outline);
select count(*) as invalid_classes from db_class where class_name='oos08_bad';
drop table oos08_char;
drop table oos08_fixed;
drop table oos08_like;
drop table oos08_policy;
