create table database(id int);
create table day_millisecond(id int);
create table day_second(id int);
create table day_minute(id int);
create table day_hour(id int);
create table distinctrow(id int);
create table div(id int);
create table do(id int);
create table duplicate(id int);
create table hour_millisecond(id int);
create table hour_second(id int);
create table hour_minute(id int);
create table localtime(id int);
create table localtimestamp(id int);
create table minute_millisecond(id int);
create table minute_second(id int);
create table mod(id int);
create table rollup(id int);
create table second_millisecond(id int);
create table truncate(id int);
create table xor(id int);
create table year_month(id int);
create table adddate(id int);
create table bit_and(id int);
create table bit_or(id int);
create table bit_xor(id int);
create table date_add(id int);
create table date_sub(id int);
create table ifnull(id int);
create table isnull(id int);
create table lcase(id int);
create table quarter(id int);
create table str_to_date(id int);
create table subdate(id int);
create table ucase(id int);
create table week(id int);

create table x1(database int);
create table x2(day_millisecond int);
create table x3(day_second int);
create table x4(day_minute int);
create table x5(day_hour int);
create table x6(distinctrow int);
create table x7(div int);
create table x8(do int);
create table x9(duplicate int);
create table x10(hour_millisecond int);
create table x11(hour_second int);
create table x12(hour_minute int);
create table x13(localtime int);
create table x14(localtimestamp int);
create table x15(minute_millisecond int);
create table x16(minute_second int);
create table x17(mod int);
create table x18(rollup int);
create table x19(second_millisecond int);
create table x20(truncate int);
create table x21(xor int);
create table x22(year_month int);
create table x23(adddate int);
create table x24(bit_and int);
create table x25(bit_or int);
create table x26(bit_xor int);
create table x27(date_add int);
create table x28(date_sub int);
create table x29(ifnull int);
create table x30(isnull int);
create table x31(lcase int);
create table x32(quarter int);
create table x33(str_to_date int);
create table x34(subdate int);
create table x35(ucase int);
create table x36(week int);

drop table adddate;
drop table bit_and;
drop table bit_or;
drop table bit_xor;
drop table date_add;
drop table date_sub;
drop table ifnull;
drop table isnull;
drop table lcase;
drop table quarter;
drop table str_to_date;
drop table subdate;
drop table ucase;
drop table week;

drop table x23;
drop table x24;
drop table x25;
drop table x26;
drop table x27;
drop table x28;
drop table x29;
drop table x30;
drop table x31;
drop table x32;
drop table x33;
drop table x34;
drop table x35;
drop table x36;