/* 4. BIGINT implicit conversions */

-- ===========================================================================
-- Section 1: BIGINT conversions
-- ===========================================================================

evaluate '1-1. BIGINT + BIGINT => BIGINT';
SELECT CAST(2 AS BIGINT) + CAST(1 AS BIGINT),
       TYPEOF(CAST(2 AS BIGINT) + CAST(1 AS BIGINT));

evaluate '1-2. BIGINT + Fixed NUMERIC => Float NUMERIC';
SELECT CAST(2 AS BIGINT) + CAST(1 AS NUMERIC(1)),
       TYPEOF(CAST(2 AS BIGINT) + CAST(1 AS NUMERIC(1)));

evaluate '1-3. BIGINT + Float NUMERIC => Float NUMERIC';
SELECT CAST(2 AS BIGINT) + CAST(1 AS NUMERIC),
       TYPEOF(CAST(2 AS BIGINT) + CAST(1 AS NUMERIC));

evaluate '1-4. BIGINT + FLOAT => FLOAT';
SELECT CAST(2 AS BIGINT) + CAST(1 AS FLOAT),
       TYPEOF(CAST(2 AS BIGINT) + CAST(1 AS FLOAT));

evaluate '1-5. BIGINT + DOUBLE => DOUBLE';
SELECT CAST(2 AS BIGINT) + CAST(1 AS DOUBLE),
       TYPEOF(CAST(2 AS BIGINT) + CAST(1 AS DOUBLE));

evaluate '1-6. BIGINT + high-precision Float NUMERIC preserves full precision';
-- integer + Float NUMERIC stays NUMERIC (not DOUBLE), so all 38 digits survive
SELECT CAST(1 AS BIGINT) + CAST(0.12345678901234567890123456789012345678 AS NUMERIC),
       TYPEOF(CAST(1 AS BIGINT) + CAST(0.12345678901234567890123456789012345678 AS NUMERIC));

evaluate '1-7. BIGINT with -, *, / and NUMERIC, and BIGINT / BIGINT integer division';
SELECT CAST(2 AS BIGINT) - CAST(1 AS NUMERIC),
       TYPEOF(CAST(2 AS BIGINT) - CAST(1 AS NUMERIC));
SELECT CAST(2 AS BIGINT) * CAST(3 AS NUMERIC),
       TYPEOF(CAST(2 AS BIGINT) * CAST(3 AS NUMERIC));
SELECT CAST(1 AS BIGINT) / CAST(3 AS NUMERIC),
       TYPEOF(CAST(1 AS BIGINT) / CAST(3 AS NUMERIC));
SELECT CAST(1 AS BIGINT) / CAST(3 AS BIGINT),
       TYPEOF(CAST(1 AS BIGINT) / CAST(3 AS BIGINT));

evaluate '1-8. BIGINT + BIGINT overflow behavior';
SELECT CAST(9223372036854775807 AS BIGINT) + CAST(1 AS BIGINT),
       TYPEOF(CAST(9223372036854775807 AS BIGINT) + CAST(1 AS BIGINT));
