drop table if exists t;
create table t(i int) partition by range(i)(partition p1 values less than(10),partition p2 values less than(100));
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p1 into (partition p1n1 values less than(10),partition p1n2 values less than(5));

drop table if exists t;
create table t(i int) partition by range(i)(partition p1 values less than(10),partition p2 values less than(100));
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p2 into (partition p1n1 values less than(100),partition p1n2 values less than(20));

drop table if exists t;
create table t(i varchar(2000)) partition by range(i)(partition p1 values less than('B'),partition p2 values less than('d'));
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p2 into (partition p1n1 values less than('BUILD'),partition p1n2 values less than('d'));
select * from t partition(p1) order by 1;
select * from t partition(p1n1);
select * from t partition(p1n2) order by 1;

drop table if exists t;
create table t(i date) partition by range(i)(partition p1 values less than('20140101'),partition p2 values less than('2015-12-31'));
insert into t values('20140201');
insert into t values('20140301');
insert into t  values('20140930');
alter table t reorganize partition p2 into (partition p1n1 values less than('20140630'),partition p1n2 values less than('20151231'));
select * from t partition(p1) order by 1;
select * from t partition(p1n1) order by 1;
select * from t partition(p1n2) order by 1;

drop table if exists t;
create table t(i date) partition by range(i)(partition p1 values less than('20140101'),partition p2 values less than('2015-12-31'));
insert into t values('20140201');
insert into t values('20140301');
insert into t  values('20140930');
alter table t reorganize partition p2 into (partition p1n1 values less than('20151231'),partition p1n2 values less than('20150630'));
select * from t partition(p1) order by 1;
select * from t partition(p1n1) order by 1;
select * from t partition(p1n2) order by 1;
drop table if exists t;
create table t(i datetime) partition by range(i)(partition p1 values less than('20140101'),partition p2 values less than('2015-12-31'));
insert into t values('20140201');
insert into t values('20140301');
insert into t  values('20140930');
alter table t reorganize partition p2 into (partition p1n1 values less than('20151231'),partition p1n2 values less than('20150630'));
select * from t partition(p1) order by 1;
select * from t partition(p1n1) order by 1;
select * from t partition(p1n2) order by 1;
drop table if exists t;
create table t(i time) partition by range(i)(partition p1 values less than('121212'),partition p2 values less than('121256'));
alter table t reorganize partition p2 into (partition p1n1 values less than('121256'),partition p1n2 values less than('121230'));
insert into t values('121201');
insert into t values('121224');
insert into t values('121245');
select * from t partition(p1) order by 1;
select * from t partition(p1n1) order by 1;
select * from t partition(p1n2) order by 1;
drop table if exists t;
create table t(i timestamp) partition by range(i)(partition p1 values less than('2014-01-01 12:12:12'),partition p2 values less than('2014-12-31 12:12:56'));
alter table t reorganize partition p2 into (partition p1n1 values less than('2014-12-31 12:12:56'),partition p1n2 values less than('2014-12-30 12:12:50'));
insert into t values('121201');
insert into t values('121224');
insert into t values('121230');
select * from t partition(p1) order by 1;
select * from t partition(p1n1) order by 1;
select * from t partition(p1n2) order by 1;
drop table if exists t;
create table t(i int) partition by range(i)(partition p1 values less than(10),partition p2 values less than maxvalue);
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p2 into (partition p1n1 values less than(100),partition p1n2 values less than maxvalue);

drop table if exists t;
create table t(i bigint) partition by range(i)(partition p1 values less than(10),partition p2 values less than maxvalue);
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p2 into (partition p1n1 values less than(5),partition p1n2 values less than maxvalue);
drop table if exists t;
create table t(i smallint) partition by range(i)(partition p1 values less than(10),partition p2 values less than maxvalue);
insert into t values(1);
insert into t values(25);
insert into t  values(99);
alter table t reorganize partition p2 into (partition p1n1 values less than(15),partition p1n2 values less than maxvalue);
insert into t values(11);
select * from t partition(p1n1);
 select * from t partition(p1n2) order by 1;
 drop t;
