drop if exists tx_serial;
CREATE TABLE tx_serial (id INT);
create serial BUFFER  start with 1;
create serial CLOSE start with 2;
create serial COMMENT start with 3;
create serial CRITICAL start with 4;
create serial DBLINK start with 5;
create serial DBNAME start with 6;
create serial DISK_SIZE start with 7;
create serial DONT_REUSE_OID start with 8;
create serial HOST start with 9;
create serial INVISIBLE start with 10;
create serial JOB start with 11;
create serial NULLS start with 12;
create serial OPEN start with 13;
create serial PATH start with 14;
create serial PERCENTILE_CONT start with 15;
create serial PERCENTILE_DISC start with 16;
create serial PORT start with 17;
create serial PROPERTIES start with 18;
create serial QUEUES start with 19;
create serial RESPECT start with 20;
create serial SECTIONS start with 21;
create serial SERVER start with 22;
create serial THREADS start with 23;
create serial TRAN start with 24;
create serial VISIBLE start with 25;
create serial WITHIN start with 26;

INSERT INTO tx_serial VALUES (BUFFER.NEXT_VALUE);
INSERT INTO tx_serial VALUES (CLOSE.NEXT_VALUE);
INSERT INTO tx_serial VALUES (COMMENT.NEXT_VALUE);
INSERT INTO tx_serial VALUES (CRITICAL.NEXT_VALUE);
INSERT INTO tx_serial VALUES (DBLINK.NEXT_VALUE);
INSERT INTO tx_serial VALUES (DBNAME.NEXT_VALUE);
INSERT INTO tx_serial VALUES (DISK_SIZE.NEXT_VALUE);
INSERT INTO tx_serial VALUES (DONT_REUSE_OID.NEXT_VALUE);
INSERT INTO tx_serial VALUES (HOST.NEXT_VALUE);
INSERT INTO tx_serial VALUES (INVISIBLE.NEXT_VALUE);
INSERT INTO tx_serial VALUES (JOB.NEXT_VALUE);
INSERT INTO tx_serial VALUES (NULLS.NEXT_VALUE);
INSERT INTO tx_serial VALUES (OPEN.NEXT_VALUE);
INSERT INTO tx_serial VALUES (PATH.NEXT_VALUE);
INSERT INTO tx_serial VALUES (PERCENTILE_CONT.NEXT_VALUE);
INSERT INTO tx_serial VALUES (PERCENTILE_DISC.NEXT_VALUE);
INSERT INTO tx_serial VALUES (PORT.NEXT_VALUE);
INSERT INTO tx_serial VALUES (PROPERTIES.NEXT_VALUE);
INSERT INTO tx_serial VALUES (QUEUES.NEXT_VALUE);
INSERT INTO tx_serial VALUES (RESPECT.NEXT_VALUE);
INSERT INTO tx_serial VALUES (SECTIONS.NEXT_VALUE);
INSERT INTO tx_serial VALUES (SERVER.NEXT_VALUE);
INSERT INTO tx_serial VALUES (THREADS.NEXT_VALUE);
INSERT INTO tx_serial VALUES (TRAN.NEXT_VALUE);
INSERT INTO tx_serial VALUES (VISIBLE.NEXT_VALUE);
INSERT INTO tx_serial VALUES (WITHIN.NEXT_VALUE);
select * from tx_serial;
       
drop serial BUFFER;
drop serial CLOSE;
drop serial COMMENT;
drop serial CRITICAL;
drop serial DBLINK;
drop serial DBNAME;
drop serial DISK_SIZE;
drop serial DONT_REUSE_OID;
drop serial HOST;
drop serial INVISIBLE;
drop serial JOB;
drop serial NULLS;
drop serial OPEN;
drop serial PATH;
drop serial PERCENTILE_CONT;
drop serial PERCENTILE_DISC;
drop serial PORT;
drop serial PROPERTIES;
drop serial QUEUES;
drop serial RESPECT;
drop serial SECTIONS;
drop serial SERVER;
drop serial THREADS;
drop serial TRAN;
drop serial VISIBLE;
drop serial WITHIN;

drop table tx_serial;
