drop if exists tx_serial;
CREATE TABLE tx_serial (id INT);
create serial AES START WITH 1;
create serial ARIA START WITH 2;              
create serial BENCHMARK START WITH 3;         
create serial EMPTY START WITH 4;             
create serial ENCRYPT START WITH 5;           
create serial ERROR START WITH 6;             
create serial NESTED START WITH 7;               
create serial ONLINE START WITH 8;            
create serial ORDINALITY START WITH 9;        
create serial PARALLEL START WITH 10;          
create serial REGEXP_COUNT START WITH 11;      
create serial REGEXP_INSTR START WITH 12;      
create serial REGEXP_LIKE START WITH 13;       
create serial REGEXP_REPLACE START WITH 14;    
create serial REGEXP_SUBSTR START WITH 15;     
create serial TIMEZONE START WITH 16;  

INSERT INTO tx_serial VALUES (AES.NEXT_VALUE);
INSERT INTO tx_serial VALUES (ARIA.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (BENCHMARK.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (EMPTY.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (ENCRYPT.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (ERROR.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (NESTED.NEXT_VALUE);
INSERT INTO tx_serial VALUES (ONLINE.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (ORDINALITY.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (PARALLEL.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (REGEXP_COUNT.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (REGEXP_INSTR.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (REGEXP_LIKE.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (REGEXP_REPLACE.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (REGEXP_SUBSTR.NEXT_VALUE); 
INSERT INTO tx_serial VALUES (TIMEZONE.NEXT_VALUE); 
select * from tx_serial;
       
drop serial AES;
drop serial ARIA;              
drop serial BENCHMARK;         
drop serial EMPTY;             
drop serial ENCRYPT;           
drop serial ERROR;             
drop serial NESTED;                 
drop serial ONLINE;            
drop serial ORDINALITY;        
drop serial PARALLEL;          
drop serial REGEXP_COUNT;      
drop serial REGEXP_INSTR;      
drop serial REGEXP_LIKE;       
drop serial REGEXP_REPLACE;    
drop serial REGEXP_SUBSTR;     
drop serial TIMEZONE; 

drop table tx_serial;
