--+ holdcas on;
-- workspace#356 (map #312, dpin-17d): a hash list scan copies each build key into its hash table, in the probe key's
-- domain where a key pair's types differ. The scan now decides each key's copy or conversion before its first build
-- row, from the probe key's domain as the scan reads it and the domain the plan gives the key's values, and the row
-- runs that decision. The build side is the inner derived table, kept a list by NO_MERGE and a WHERE clause, the probe
-- side the outer table. One cell per pair of key types, then keys over binds and session variables, a scan reopened
-- for every outer row, the hierarchical scan of CONNECT BY, JSON build keys, and build values the conversion refuses.
-- The trace of each query shows the hash list scan. Every answer here is develop's.
drop table if exists hk_o;
drop table if exists hk_i;
create table hk_o (k int, i int, bi bigint, si smallint, d double, f float, n numeric(10,2), n0 numeric(20,0), s varchar(20), c char(5), dt date, dtm datetime, e enum('a','b','c'), m monetary);
create table hk_i (k int, i int, bi bigint, si smallint, d double, f float, n numeric(10,2), n0 numeric(20,0), s varchar(20), c char(5), dt date, dtm datetime, e enum('a','b','c'), m monetary);
insert into hk_o values (1, 1, 1, 1, 1.0, 1.0, 1.00, 1, '1', '1', date'2020-01-01', datetime'2020-01-01 00:00:00', 'a', 1);
insert into hk_o values (2, 2, 2, 2, 2.5, 2.5, 2.50, 2, '2.5', 'abc', date'2020-01-02', datetime'2020-01-02 00:00:00', 'b', 2);
insert into hk_o values (3, 3, 3, 3, 3.0, 3.0, 3.00, 3, 'abc', 'abcde', date'2020-01-03', datetime'2020-01-03 12:00:00', 'c', 3);
insert into hk_o values (4, null, null, null, null, null, null, null, null, null, null, null, null, null);
insert into hk_i select * from hk_o;
insert into hk_i values (5, 5, 5, 5, 5.0, 5.0, 5.00, 5, '5', '5', date'2020-01-05', datetime'2020-01-05 00:00:00', 'a', 5);
insert into hk_i values (6, 3, 3, 3, 3.0, 3.0, 3.00, 3, 'a', 'a', date'2020-01-03', datetime'2020-01-03 00:00:00', 'a', 3);

-- [FIXED] the compiler fixes both key domains
set trace on;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.bi = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i = b.bi order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i = b.d order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.d = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.n = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i = b.n order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.n0 = b.n order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.si = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.f = b.d order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.c = b.s order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.s = b.c order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k <> 3 and k <> 6) b where a.s = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k <> 3 and k <> 6) b where a.i = b.s order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.dt = b.dtm order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.dtm = b.dt order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.e = b.s order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.s = b.e order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.m = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i = b.i and a.bi = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.d = b.i + 0.5 order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + 1 = b.bi order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.c from hk_o a, (select /*+ NO_MERGE */ i, count(*) c from hk_i group by i) b where a.bi = b.i order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a left outer join (select /*+ NO_MERGE */ * from hk_i where k > 0) b on a.bi = b.i order by 1, 2;
show trace;

-- [BIND] a probe key or a build key over a bind: the gate decides its domain
prepare hk_b1 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + ? = b.i order by 1, 2';
execute hk_b1 using 0;
show trace;
execute hk_b1 using 1;
execute hk_b1 using 0.5;
execute hk_b1 using '0';
execute hk_b1 using null;
prepare hk_b2 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + ? = b.bi order by 1, 2';
execute hk_b2 using 0;
show trace;
execute hk_b2 using 0.5;
prepare hk_b3 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i * ? = b.d order by 1, 2';
execute hk_b3 using 1;
show trace;
execute hk_b3 using 2.5;
prepare hk_b4 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, ? v from hk_i where k > 0) b where a.i = b.v order by 1, 2';
execute hk_b4 using 1;
show trace;
execute hk_b4 using 1.0;
execute hk_b4 using '1';
execute hk_b4 using null;
prepare hk_b5 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + ? v from hk_i where k > 0) b where a.bi = b.v order by 1, 2';
execute hk_b5 using 0;
show trace;
execute hk_b5 using 0.5;
prepare hk_b6 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + ? v from hk_i where k > 0) b where a.i + ? = b.v order by 1, 2';
execute hk_b6 using 0, 0;
show trace;
execute hk_b6 using 0.5, 0;
execute hk_b6 using 0, 0.5;
execute hk_b6 using 0, 0.0;
execute hk_b6 using 0.0, 0;
-- two keys: the second pair's types differ
prepare hk_b8 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i, i + ? v from hk_i where k > 0) b where a.i + ? = b.v and a.bi = b.i order by 1, 2';
execute hk_b8 using 0, 0;
show trace;
execute hk_b8 using 0, 0.0;
-- a hash list scan reopened for every outer row
prepare hk_b7 from 'select a.k, (select count(*) from hk_o x, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where x.i + ? = b.i and x.k = a.k) c from hk_o a order by 1';
execute hk_b7 using 0;
show trace;
execute hk_b7 using 0.5;
prepare hk_b9 from 'select a.k, (select count(*) from hk_o x, (select /*+ NO_MERGE */ k, i + ? v from hk_i where k > 0) b where x.i + ? = b.v and x.k = a.k) c from hk_o a order by 1';
execute hk_b9 using 0, 0;
show trace;
execute hk_b9 using 0, 0.0;
execute hk_b9 using 0.0, 0;
execute hk_b9 using 0, 0e0;
execute hk_b9 using 0e0, 0;
execute hk_b6 using 0, 0e0;
execute hk_b6 using 0e0, 0;
-- a probe key whose string collation the bind gives
prepare hk_b10 from 'select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where b.c = concat(a.s, ?) order by 1, 2';
execute hk_b10 using '';
show trace;
execute hk_b10 using 'x';

-- [SESSION VARIABLE] a key over a session variable read
set @hk_v = 0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + @hk_v = b.i order by 1, 2;
show trace;
set @hk_v = 0.5;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + @hk_v = b.i order by 1, 2;
set @hk_v = '0';
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + @hk_v = b.i order by 1, 2;
set @hk_v = 0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ * from hk_i where k > 0) b where a.i + @hk_v = b.i + 0 order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + @hk_v v from hk_i where k > 0) b where a.bi = b.v order by 1, 2;
show trace;
set @hk_v = 0.5;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + @hk_v v from hk_i where k > 0) b where a.bi = b.v order by 1, 2;
set @hk_v = 0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, (@hk_v := @hk_v + 1) v from hk_i where k > 0) b where a.bi = b.v order by 1, 2;
show trace;
set @hk_v = 0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + @hk_v v from hk_i where k > 0) b where a.i + @hk_v = b.v order by 1, 2;
show trace;
set @hk_v = 0.0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i + 0 v from hk_i where k > 0) b where a.i + @hk_v = b.v order by 1, 2;
show trace;
set @hk_v = 0;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i v from hk_i where k > 0) b where a.bi = b.v + @hk_v order by 1, 2;
show trace;
set @hk_v = 0.5;
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i v from hk_i where k > 0) b where a.bi = b.v + @hk_v order by 1, 2;
set @hk_v = '0';
select /*+ ordered */ a.k, b.k from hk_o a, (select /*+ NO_MERGE */ k, i v from hk_i where k > 0) b where a.bi = b.v + @hk_v order by 1, 2;
set trace off;

-- [CONNECT BY] the hierarchical hash list scan over a join: the prior key against the build key
drop table if exists hk_q;
drop table if exists hk_q2;
create table hk_q (id int, pid bigint, name varchar(10));
create table hk_q2 (qid int, job varchar(10));
insert into hk_q values (1, null, 'r'), (2, 1, 'c1'), (3, 1, 'c2'), (4, 2, 'g1');
insert into hk_q2 values (1, 'p'), (2, 'q'), (3, 'r'), (4, 's'), (5, 't');
set trace on;
select q.id, q.pid, q2.job, level from hk_q q inner join hk_q2 q2 on q.id = q2.qid start with q.pid is null connect by prior q.id = q.pid order by 1, 2, 3, 4;
show trace;
select q.id, q.pid, q2.job, level from hk_q q inner join hk_q2 q2 on q.id = q2.qid start with q.pid is null connect by q.pid = prior q.id order by 1, 2, 3, 4;
show trace;
select q.id, q.pid, q2.job, level from hk_q q inner join hk_q2 q2 on q.id = q2.qid start with q.pid is null connect by prior q.pid = q.id order by 1, 2, 3, 4;
show trace;
set trace off;
insert into hk_q values (5, 3000000000, 'x');
select q.id, q.pid, q2.job, level from hk_q q inner join hk_q2 q2 on q.id = q2.qid start with q.pid is null connect by prior q.id = q.pid order by 1, 2, 3, 4;
select q.id, q.pid, q2.job, level from hk_q q inner join hk_q2 q2 on q.id = q2.qid start with q.pid is null connect by prior q.pid = q.id order by 1, 2, 3, 4;

-- [REFUSED] build values the conversion into the probe key's domain refuses, each on its own table
create table hk_r (k int, i int, si smallint, c char(3), st set(int), ms multiset(int), sq sequence(int));
insert into hk_r values (1, 1, 1, 'abc', {1, 2}, {1, 2}, {1, 2}), (2, 2, 2, 'x', {3}, {3, 3}, {3});
create table hk_r1 (k int, bi bigint);
insert into hk_r1 values (1, 1), (2, 3000000000);
set trace on;
select /*+ ordered */ a.k, b.bi from hk_r a, (select /*+ NO_MERGE */ * from hk_r1 where k > 0) b where a.i = b.bi order by 1, 2;
show trace;
select /*+ ordered no_hash_list_scan */ a.k, b.bi from hk_r a, (select /*+ NO_MERGE */ * from hk_r1 where k > 0) b where a.i = b.bi order by 1, 2;
create table hk_r2 (k int, d double);
insert into hk_r2 values (1, 1), (2, 1e20);
select /*+ ordered */ a.k, b.d from hk_r a, (select /*+ NO_MERGE */ * from hk_r2 where k > 0) b where a.i = b.d order by 1, 2;
show trace;
create table hk_r3 (k int, i int);
insert into hk_r3 values (1, 1), (2, 100000);
select /*+ ordered */ a.k, b.i from hk_r a, (select /*+ NO_MERGE */ * from hk_r3 where k > 0) b where a.si = b.i order by 1, 2;
show trace;
create table hk_r4 (k int, s varchar(10));
insert into hk_r4 values (1, 'abc'), (2, 'abcdefgh');
select /*+ ordered */ a.k, b.s from hk_r a, (select /*+ NO_MERGE */ * from hk_r4 where k > 0) b where a.c = b.s order by 1, 2;
show trace;
select /*+ ordered no_hash_list_scan */ a.k, b.s from hk_r a, (select /*+ NO_MERGE */ * from hk_r4 where k > 0) b where a.c = b.s order by 1, 2;
create table hk_r5 (k int, s varchar(10));
insert into hk_r5 values (1, '1'), (2, 'x');
select /*+ ordered */ a.k, b.s from hk_r a, (select /*+ NO_MERGE */ * from hk_r5 where k > 0) b where a.i = b.s order by 1, 2;
show trace;
create table hk_r6 (k int, st set(int), ms multiset(int), sq sequence(int));
insert into hk_r6 values (1, {1, 2}, {1, 2}, {1, 2}), (2, {3}, {3, 3}, {3});
select /*+ ordered */ a.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r6 where k > 0) b where a.st = b.ms order by 1;
show trace;
select /*+ ordered */ a.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r6 where k > 0) b where a.ms = b.st order by 1;
select /*+ ordered */ a.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r6 where k > 0) b where a.sq = b.st order by 1;
select /*+ ordered */ a.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r6 where k > 0) b where a.st = b.st order by 1;
create table hk_r8 (k int, j json);
insert into hk_r8 values (1, '1'), (2, '"x"'), (3, '2.0');
select /*+ ordered */ a.k, b.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r8 where k > 0) b where a.i = b.j order by 1, 2;
show trace;
select /*+ ordered */ a.k, b.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r8 where k > 0) b where a.c = b.j order by 1, 2;
select /*+ ordered */ a.k, b.k from hk_r a, (select /*+ NO_MERGE */ * from hk_r8 where k > 1) b where a.i = b.j order by 1, 2;
create table hk_r7 (k int, n numeric(38,0));
insert into hk_r7 values (1, 1), (2, 99999999999999999999999999999999999999);
select /*+ ordered */ a.k, b.n from hk_r a, (select /*+ NO_MERGE */ * from hk_r7 where k > 0) b where a.i = b.n order by 1, 2;
show trace;
set trace off;

deallocate prepare hk_b1;
deallocate prepare hk_b2;
deallocate prepare hk_b3;
deallocate prepare hk_b4;
deallocate prepare hk_b5;
deallocate prepare hk_b6;
deallocate prepare hk_b7;
deallocate prepare hk_b8;
deallocate prepare hk_b9;
deallocate prepare hk_b10;
deallocate variable @hk_v;
drop table hk_r1;
drop table hk_r2;
drop table hk_r3;
drop table hk_r4;
drop table hk_r5;
drop table hk_r6;
drop table hk_r7;
drop table hk_r8;
drop table hk_r;
drop table hk_q;
drop table hk_q2;
drop table hk_o;
drop table hk_i;
--+ holdcas off;
commit;
