--+ holdcas on;
set system parameters 'compat_mode=cubrid';
select sqrt(cast(1 as SHORT)) from db_root;
select sqrt(cast(1 as INTEGER)) from db_root;
select sqrt(cast(1 as BIGINT)) from db_root;
select sqrt(cast(1 as FLOAT)) from db_root;
select sqrt(cast(1 as DOUBLE)) from db_root;
select sqrt(cast(1 as NUMERIC(15,5))) from db_root;
select sqrt(cast(1 as MONETARY)) from db_root;
select sqrt(cast(-1 as SHORT)) from db_root;
select sqrt(cast(-1 as INTEGER)) from db_root;
select sqrt(cast(-1 as BIGINT)) from db_root;
select sqrt(cast(-1 as FLOAT)) from db_root;
select sqrt(cast(-1 as DOUBLE)) from db_root;
select sqrt(cast(-1 as NUMERIC(15,5))) from db_root;
select sqrt(cast(-1 as MONETARY)) from db_root;
commit;
--+ holdcas off;
