--+ server-message on

select 'This test produces a compilation error. ( t_compile_error_date, float )' ;
create or replace procedure t_compile_error_date_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_date = ' ||  NVL(left_date,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_date * right_float = '||left_date * right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_date, float )' ;
create or replace procedure t_compile_error_date_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_date = ' ||  NVL(left_date,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_date / right_float = '||left_date / right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_time, float )' ;
create or replace procedure t_compile_error_time_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_time = ' ||  NVL(left_time,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_time * right_float = '||left_time * right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_time, float )' ;
create or replace procedure t_compile_error_time_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_time = ' ||  NVL(left_time,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_time / right_float = '||left_time / right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_datetime, float )' ;
create or replace procedure t_compile_error_datetime_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_datetime = ' ||  NVL(left_datetime,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_datetime * right_float = '||left_datetime * right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_datetime, float )' ;
create or replace procedure t_compile_error_datetime_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_datetime = ' ||  NVL(left_datetime,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_datetime / right_float = '||left_datetime / right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_timestamp, float )' ;
create or replace procedure t_compile_error_timestamp_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_timestamp = ' ||  NVL(left_timestamp,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_timestamp * right_float = '||left_timestamp * right_float ) ; 
    dbms_output.put_line('');
end;

select 'This test produces a compilation error. ( t_compile_error_timestamp, float )' ;
create or replace procedure t_compile_error_timestamp_float( tc_comment string ) as 
    left_boolean                   boolean       := TRUE;
    left_string                    string        := '123';
    left_string_null               string        := NULL;
    left_string_boolean         string        := 'TRUE';
    left_string_short              string        := '8934';                             
    left_string_int                string        := '78234';                            
    left_string_bigint             string        := '278234';                           
    left_string_numeric            string        := '5678.123';                         
    left_string_float              string        := '3677.345';                        
    left_string_double             string        := '56789.1234';                       
    left_string_date               string        := '2024-03-05';                 
    left_string_time               string        := '23:59:59';                   
    left_string_datetime           string        := '2024-03-01 22:15:25'; 
    left_string_timestamp          string        := '2024-05-05 23:30:45';
    left_short                     short         := 8934;
    left_int                       int           := 78234;
    left_bigint                    bigint        := 278234;
    left_numeric                   numeric(8,4)  := 5678.123;
    left_float                     float         := 3677.345;
    left_double                    double        := 56789.1234;
    left_date                      date          := DATE'2024-03-05';
    left_time                      time          := TIME'23:59:59';
    left_datetime                  datetime      := DATETIME'2024-03-01 22:15:25';
    left_timestamp                 timestamp     := TIMESTAMP'2024-05-05 23:30:45';
    left_sys_refcursor             sys_refcursor ;
    cursor  left_cursor is select * from dual ;
    
    right_boolean                 boolean       := FALSE;
    right_string                  string        := '999';
    right_string_null             string        := NULL; 
    right_string_boolean        string        := 'FALSE'; 
    right_string_short            string        := '34';                               
    right_string_int              string        := '234';                              
    right_string_bigint           string        := '1234';                             
    right_string_numeric          string        := '1234.567';                         
    right_string_float            string        := '432.321';                        
    right_string_double           string        := '1234.56789';                 
    right_string_date             string        := '2002-03-05';                 
    right_string_time             string        := '03:59:59';               
    right_string_datetime         string        := '2002-02-02 02:22:22';
    right_string_timestamp        string        := '2002-01-01 01:01:01';
    right_short                   short         := 34;
    right_int                     int           := 234;
    right_bigint                  bigint        := 1234;
    right_numeric                 numeric(8,4)  := 1234.567;
    right_float                   float         := 432.321;
    right_double                  double        := 1234.56789;
    right_date                    date          := DATE'2002-03-05';
    right_time                    time          := TIME'03:59:59';
    right_datetime                datetime      := DATETIME'2002-02-02 02:22:22';
    right_timestamp               timestamp     := TIMESTAMP'2002-01-01 01:01:01';
    right_sys_refcursor           sys_refcursor ;
    cursor  right_cursor is select * from dual ;
begin 

    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_timestamp = ' ||  NVL(left_timestamp,'NULL')  ); 
    dbms_output.put_line('right_float = ' ||NVL(right_float,'NULL')  ); 
    dbms_output.put_line('***************************************');
    dbms_output.put_line('left_timestamp / right_float = '||left_timestamp / right_float ) ; 
    dbms_output.put_line('');
end;

--+ server-message off
