create table parent (a int primary key);
create table child1 (a int, b int primary key, foreign key (a) references parent(a) on delete CASCADE);
create table child2 (a int, b int primary key, foreign key (a) references parent(a) on delete CASCADE);
create table grand_child1 (b int, c int primary key, foreign key (b) references child1(b) on delete CASCADE);
create table grand_child2 (b int, c int primary key, foreign key (b) references child1(b));
create table grand_child3 (b int, c int primary key, foreign key (b) references child2(b) on delete CASCADE);
create table grand_child4 (b int, c int primary key, foreign key (b) references child2(b) on delete CASCADE);
insert into parent values(3);
insert into child1 values(3,3);
insert into child2 values(3,3);
insert into grand_child1 values(3,3);
insert into grand_child2 values(3,3);
insert into grand_child3 values(3,3);
insert into grand_child4 values(3,3);
truncate parent cascade;
select count(*) from parent;
select count(*) from child1;
select count(*) from child2;
select count(*) from grand_child1;
select count(*) from grand_child2;
select count(*) from grand_child3;
select count(*) from grand_child4;
drop grand_child1;
drop grand_child2;
drop grand_child3;
drop grand_child4;
drop child1;
drop child2;
drop parent;
