autocommit off;
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          50,           50, 'YB', 'YB', 
                          0,            0,       4310.1,       4310.1, 
               1622650111.2, 1622650111.2, 
               'NFBRRYJNVABNRAJBKRPYWNCRKSXTGBTIQTZJGZSTQBQXH',
               'NFBRRYJNVABNRAJBKRPYWNCRKSXTGBTIQTZJGZSTQBQXH',
               '05:16:21', '05:16:21', '10/14/1980', '10/14/1980', 
               '05:16:21  10/14/1980', '05:16:21  10/14/1980', 
                357571488.0,  357571488.0,            0,            0, 
                          2,            2,            0,            0, 
                          0,            0,            0,            0, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          51,           51, 'ZB', 'ZB', 
                      15941,        15941,      29413.5,      29413.5, 
               1952509567.1, 1952509567.1, 
               'XNNIZ',
               'XNNIZ',
               '22:04:30', '22:04:30', '04/03/1981', '04/03/1981', 
               '22:04:30  04/03/1981', '22:04:30  04/03/1981', 
                824939008.0,  824939008.0,            1,            1, 
                          3,            3,            1,            1, 
                          1,            1,            1,            1, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          52,           52, 'AC', 'AC', 
                       9079,         9079,      29943.1,      29943.1, 
               1137623807.5, 1137623807.5, 
               'YBTUVDARWQTSZXGHJNPVKVHKNMHEDOUANMYTOXQVEFSDC',
               'YBTUVDARWQTSZXGHJNPVKVHKNMHEDOUANMYTOXQVEFSDC',
               '00:42:56', '00:42:56', '01/12/1976', '01/12/1976', 
               '00:42:56  01/12/1976', '00:42:56  01/12/1976', 
                515204544.0,  515204544.0,            0,            0, 
                          0,            0,            2,            2, 
                          2,            2,            2,            2, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          53,           53, 'BC', 'BC', 
                       5927,         5927,      10404.8,      10404.8, 
               1904797951.1, 1904797951.1, 
               'DRKKMDPVPYODZKDOGMMYDFIQDQQUGMKFAXLDYKDXCEBJGDULJLVYQFRXGWMNPVTM',
               'DRKKMDPVPYODZKDOGMMYDFIQDQQUGMKFAXLDYKDXCEBJGDULJLVYQFRXGWMNPVTM',
               '19:41:42', '19:41:42', '08/13/1991', '08/13/1991', 
               '19:41:42  08/13/1991', '19:41:42  08/13/1991', 
               2119878784.0, 2119878784.0,            1,            1, 
                          1,            1,            3,            3, 
                          3,            3,            3,            3, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          54,           54, 'CC', 'CC', 
                      31273,        31273,      27893.6,      27893.6, 
                621301823.7,  621301823.7, 
               'NCKOWLSWSUSTAXNMBSMRRFXWXODLZFLINWLMUJFZDQQAAUSIKRRFV',
               'NCKOWLSWSUSTAXNMBSMRRFXWXODLZFLINWLMUJFZDQQAAUSIKRRFV',
               '04:45:37', '04:45:37', '10/03/1986', '10/03/1986', 
               '04:45:37  10/03/1986', '04:45:37  10/03/1986', 
                459244064.0,  459244064.0,            0,            0, 
                          2,            2,            4,            4, 
                          4,            4,            4,            4, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          55,           55, 'DC', 'DC', 
                       6997,         6997,       2656.1,       2656.1, 
                834991551.6,  834991551.6, 
               'YKGRHUUKHFAEZGVDKPEVEZGGCFQSUSTRQBPFISDTNOPISDEMWVOTIDNIPNLGJKLMKHCJGRRNSSYLYILNRKPZDRIONVAHQO',
               'YKGRHUUKHFAEZGVDKPEVEZGGCFQSUSTRQBPFISDTNOPISDEMWVOTIDNIPNLGJKLMKHCJGRRNSSYLYILNRKPZDRIONVAHQO',
               '05:50:41', '05:50:41', '04/28/1991', '04/28/1991', 
               '05:50:41  04/28/1991', '05:50:41  04/28/1991', 
                978719104.0,  978719104.0,            1,            1, 
                          3,            3,            0,            0, 
                          5,            5,            5,            5, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          56,           56, 'EC', 'EC', 
                      26773,        26773,        723.6,        723.6, 
                345205663.8,  345205663.8, 
               'SLPTZSHTEAMCEXUTLAPNBOKFKQRSOHVJRIACNUFBBESHBMLNLDHVSPRIBZOAWAJMOTRNA',
               'SLPTZSHTEAMCEXUTLAPNBOKFKQRSOHVJRIACNUFBBESHBMLNLDHVSPRIBZOAWAJMOTRNA',
               '08:36:36', '08:36:36', '12/06/1972', '12/06/1972', 
               '08:36:36  12/06/1972', '08:36:36  12/06/1972', 
                270438656.0,  270438656.0,            0,            0, 
                          0,            0,            1,            1, 
                          6,            6,            6,            6, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          57,           57, 'FC', 'FC', 
                      18115,        18115,      31260.7,      31260.7, 
                766490559.6,  766490559.6, 
               'ZGGLVXGTSLGRDFCOAEPLCRJVDZACMUYGJTMTRRTAFFOQQJFGQETEBRDYMQXAPSMBLNUBLZMILTFEJYZGBD',
               'ZGGLVXGTSLGRDFCOAEPLCRJVDZACMUYGJTMTRRTAFFOQQJFGQETEBRDYMQXAPSMBLNUBLZMILTFEJYZGBD',
               '04:50:22', '04:50:22', '02/15/1982', '02/15/1982', 
               '04:50:22  02/15/1982', '04:50:22  02/15/1982', 
                910297856.0,  910297856.0,            1,            1, 
                          1,            1,            2,            2, 
                          7,            7,            7,            7, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          58,           58, 'GC', 'GC', 
                      10722,        10722,      23380.8,      23380.8, 
               1238616703.4, 1238616703.4, 
               'TVSKYPJOLKGCKMHCFUNRWGSGJCLGUMAGRLEZDUYEPBJHNVVSIUQBBDTBNYFFCSSMGSJFGLMWZLANATPVIGNLKZ',
               'TVSKYPJOLKGCKMHCFUNRWGSGJCLGUMAGRLEZDUYEPBJHNVVSIUQBBDTBNYFFCSSMGSJFGLMWZLANATPVIGNLKZ',
               '07:08:59', '07:08:59', '11/25/1992', '11/25/1992', 
               '07:08:59  11/25/1992', '07:08:59  11/25/1992', 
               1373365888.0, 1373365888.0,            0,            0, 
                          2,            2,            3,            3, 
                          8,            8,            8,            8, '@');
INSERT INTO x_virtual_c0  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr3_smallint_idx,       
                 attr3_smallint_noidx,     
                 attr4_float_idx,          
                 attr4_float_noidx,        
                 attr5_double_idx,         
                 attr5_double_noidx,       
                 attr6_longstr_idx,        
                 attr6_longstr_noidx,      
                 attr7_time_idx,           
                 attr7_time_noidx,         
                 attr8_date_idx,           
                 attr8_date_noidx,         
                 attr9_utime_idx,          
                 attr9_utime_noidx,        
                 attr10_money_idx,         
                 attr10_money_noidx,       
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          59,           59, 'HC', 'HC', 
                      15337,        15337,      30536.1,      30536.1, 
               1483422847.3, 1483422847.3, 
               'OOEYVEBICCNAOWNRTSAERIBDXFJPEARTSCPYYLNVXPSNMEZOHNSRCOPRMOPLDNTABNIAGCJOPPYUNMQS',
               'OOEYVEBICCNAOWNRTSAERIBDXFJPEARTSCPYYLNVXPSNMEZOHNSRCOPRMOPLDNTABNIAGCJOPPYUNMQS',
               '17:32:16', '17:32:16', '06/14/1979', '06/14/1979', 
               '17:32:16  06/14/1979', '17:32:16  06/14/1979', 
               1300383360.0, 1300383360.0,            1,            1, 
                          3,            3,            4,            4, 
                          9,            9,            9,            9, '@');
SELECT COUNT(*) FROM x_base_c0
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
ROLLBACK WORK;
SELECT COUNT(*) FROM x_base_c0
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
