autocommit off;
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          60,           60, 'IC', 'IC', 
                          0,            0,            0,            0,       
                          0,            0,            0,            0,       
                         10,           10, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          61,           61, 'JC', 'JC', 
                          1,            1,            1,            1,       
                          1,            1,            1,            1,       
                         11,           11, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          62,           62, 'KC', 'KC', 
                          0,            0,            2,            2,       
                          2,            2,            2,            2,       
                         12,           12, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          63,           63, 'LC', 'LC', 
                          1,            1,            3,            3,       
                          3,            3,            3,            3,       
                         13,           13, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          64,           64, 'MC', 'MC', 
                          0,            0,            0,            0,       
                          4,            4,            4,            4,       
                         14,           14, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          65,           65, 'NC', 'NC', 
                          1,            1,            1,            1,       
                          0,            0,            5,            5,       
                         15,           15, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          66,           66, 'OC', 'OC', 
                          0,            0,            2,            2,       
                          1,            1,            6,            6,       
                         16,           16, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          67,           67, 'PC', 'PC', 
                          1,            1,            3,            3,       
                          2,            2,            7,            7,       
                         17,           17, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          68,           68, 'QC', 'QC', 
                          0,            0,            0,            0,       
                          3,            3,            8,            8,       
                         18,           18, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          69,           69, 'RC', 'RC', 
                          1,            1,            1,            1,       
                          4,            4,            9,            9,       
                         19,           19, '@');
SELECT COUNT(*) FROM x_base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
ROLLBACK WORK;
SELECT COUNT(*) FROM x_base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
