autocommit off;
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          80,           80, 'CD', 'CD', 
                          0,            0,            0,            0,       
                          0,            0,            0,            0,       
                         30,           30, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          81,           81, 'DD', 'DD', 
                          1,            1,            1,            1,       
                          1,            1,            1,            1,       
                         31,           31, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          82,           82, 'ED', 'ED', 
                          0,            0,            2,            2,       
                          2,            2,            2,            2,       
                         32,           32, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          83,           83, 'FD', 'FD', 
                          1,            1,            3,            3,       
                          3,            3,            3,            3,       
                         33,           33, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          84,           84, 'GD', 'GD', 
                          0,            0,            0,            0,       
                          4,            4,            4,            4,       
                         34,           34, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          85,           85, 'HD', 'HD', 
                          1,            1,            1,            1,       
                          0,            0,            5,            5,       
                         35,           35, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          86,           86, 'ID', 'ID', 
                          0,            0,            2,            2,       
                          1,            1,            6,            6,       
                         36,           36, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          87,           87, 'JD', 'JD', 
                          1,            1,            3,            3,       
                          2,            2,            7,            7,       
                         37,           37, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          88,           88, 'KD', 'KD', 
                          0,            0,            0,            0,       
                          3,            3,            8,            8,       
                         38,           38, '@');
INSERT INTO x_base_c1  (                          
                 attr1_int_unique_idx,     
                 attr1_int_unique_noidx,   
                 attr2_str_unique_idx,     
                 attr2_str_unique_noidx,   
                 attr11_int_2vals_idx,     
                 attr11_int_2vals_noidx,   
                 attr12_int_4vals_idx,     
                 attr12_int_4vals_noidx,   
                 attr13_int_5vals_idx,     
                 attr13_int_5vals_noidx,   
                 attr14_int_10vals_idx,    
                 attr14_int_10vals_noidx,  
                 attr15_int_50vals_idx,    
                 attr15_int_50vals_noidx,  
                 attr16_dep_tag_noidx)     
       VALUES (          89,           89, 'LD', 'LD', 
                          1,            1,            1,            1,       
                          4,            4,            9,            9,       
                         39,           39, '@');
SELECT COUNT(*) FROM x_base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
COMMIT WORK;
SELECT COUNT(*) FROM x_base_c1
 	WHERE attr16_dep_tag_noidx LIKE '%INITIAL ELEMENT%'
	   OR attr16_dep_tag_noidx LIKE '%@%';
