CREATE TABLE t (id int);

ALTER TABLE t add column d int default sys_date;
DESCRIBE t;

ALTER TABLE t add column d double default sys_date;

DESCRIBE t;
ALTER TABLE t add column d float default sys_date;
DESCRIBE t;
ALTER TABLE t add column d string default sys_date;
DESCRIBE t;
ALTER TABLE t add column d bigint default sys_date;
DESCRIBE t;
ALTER TABLE t add column d smallint default sys_date;
DESCRIBE t;
ALTER TABLE t add column d varchar(100) default sys_date;
DESCRIBE t;
ALTER TABLE t add column d char(100) default sys_date;
DESCRIBE t;
ALTER TABLE t add column d varnchar(100) default sys_date;
DESCRIBE t;
ALTER TABLE t add column d nchar(100) default sys_date;
DESCRIBE t;
ALTER TABLE t add column d time default sys_date;
DESCRIBE t;
ALTER TABLE t add column d int default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d double default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d float default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d string default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d bigint default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d smallint default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d varchar(100) default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d char(100) default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d varnchar(100) default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d nchar(100) default sys_datetime;
DESCRIBE t;
ALTER TABLE t add column d time default sys_datetime;
DESCRIBE t;
ALTER TABLE t drop column d;

ALTER TABLE t add column d int default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d double default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d float default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d string default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d bigint default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d smallint default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d varchar(100) default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d char(100) default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d varnchar(100) default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d nchar(100) default sys_timestamp;
DESCRIBE t;
ALTER TABLE t add column d int default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d double default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d float default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d string default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d bigint default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d smallint default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d varchar(100) default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d char(100) default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d varnchar(100) default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d nchar(100) default unix_timestamp();
DESCRIBE t;
ALTER TABLE t add column d int default user();
DESCRIBE t;
ALTER TABLE t add column d double default user();
DESCRIBE t;
ALTER TABLE t add column d float default user();
DESCRIBE t;
ALTER TABLE t add column d bigint default user();
DESCRIBE t;
ALTER TABLE t add column d smallint default user();
DESCRIBE t;
ALTER TABLE t add column d time default user();
DESCRIBE t;
ALTER TABLE t add column d int default current_user;
DESCRIBE t;
ALTER TABLE t add column d double default current_user;
DESCRIBE t;
ALTER TABLE t add column d float default current_user;
DESCRIBE t;
ALTER TABLE t add column d bigint default current_user;
DESCRIBE t;
ALTER TABLE t add column d smallint default current_user;
DESCRIBE t;
ALTER TABLE t add column d time default current_user;
DESCRIBE t;
DROP TABLE t;

