SELECT TRUNCATE(1.223,1) FROM db_root;

SELECT TRUNCATE('1.223',1) FROM db_root;

SELECT TRUNCATE('a',1) FROM db_root;

SELECT TRUNCATE(NULL,1) FROM db_root;

SELECT TRUNCATE(1.223,'1') FROM db_root;

SELECT TRUNCATE('1.223','1') FROM db_root;

SELECT TRUNCATE('a','1') FROM db_root;

SELECT TRUNCATE(NULL,'1') FROM db_root;

SELECT TRUNCATE(1.223,'a') FROM db_root;

SELECT TRUNCATE('1.223','a') FROM db_root;

SELECT TRUNCATE('a','a') FROM db_root;

SELECT TRUNCATE(NULL,'a') FROM db_root;

SELECT TRUNCATE(1.223,NULL) FROM db_root;

SELECT TRUNCATE('1.223',NULL) FROM db_root;

SELECT TRUNCATE('a',NULL) FROM db_root;

SELECT TRUNCATE(NULL,NULL) FROM db_root;

select truncate(12345678903532535312345.12345,3) from db_root;

