--+ holdcas on;

set names euckr collate euckr_bin;
select collation('a');
set names euckr collate utf8_bin;
select collation('a');
set names iso88591 collate iso88591_bin;
select collation('a');
set names iso88591 collate iso88591_en_ci;
select collation('a');
set names iso88591 collate iso88591_en_cs;
select collation('a');
set names iso88591 collate utf8_ro_cs;
select collation('a');
set names utf8 collate utf8_bin;
select collation('a');
set names utf8 collate utf8_bin;
select collation('a');
set names utf8 collate utf8_de_exp;
select collation('a');
set names utf8 collate utf8_de_exp_ai_ci;
select collation('a');
set names utf8 collate utf8_en_ci;
select collation('a');
set names utf8 collate utf8_en_cs;
select collation('a');
set names utf8 collate utf8_es_cs;
select collation('a');
set names utf8 collate utf8_fr_exp_ab;
select collation('a');
set names utf8 collate utf8_gen;
select collation('a');
set names utf8 collate utf8_gen_ai_ci;
select collation('a');
set names utf8 collate utf8_gen_ci;
select collation('a');
set names utf8 collate utf8_ja_exp;
select collation('a');
set names utf8 collate utf8_ja_exp_cbm;
select collation('a');
set names utf8 collate utf8_km_exp;
select collation('a');
set names utf8 collate utf8_ko_cs;
select collation('a');
set names utf8 collate utf8_ko_cs_uca;
select collation('a');
set names utf8 collate utf8_ro_cs;
select collation('a');
set names utf8 collate utf8_tr_cs;
select collation('a');
set names utf8 collate utf8_tr_cs_uca;
select collation('a');
set names utf8 collate utf8_vi_cs;
select collation('a');
set names utf8 collate iso88591_bin;
select collation('a');

set names iso88591;
commit;
--+ holdcas off;
