autocommit off;
call login('dba','') on class db_user;
select cast('00001111' as bit(8)) from db_root;
select cast('00001111' as bit(64)) from db_root;
select cast('1234abcd' as bit varying(8)) from db_root;
select cast('1234abcd' as bit varying(64)) from db_root;
create class cast_test ( cb char(6) );
insert into cast_test (cb) values ( 'abcd' ) ;
select cast ( cb as bit (20) ) from cast_test ;
select cast ( cb as bit (80) ) from cast_test ;
select cast ( cb as bit varying(20) ) from cast_test ;
select cast ( cb as bit varying(80) ) from cast_test ;
create class cast_test2 ( cb varchar(6) );
insert into cast_test2 (cb) values ( 'abcd' ) ;
select cast ( cb as bit (20) ) from cast_test ;
select cast ( cb as bit (80) ) from cast_test ;
select cast ( cb as bit varying(20) ) from cast_test ;
select cast ( cb as bit varying(80) ) from cast_test ;
call login('dba','') on class db_user;
rollback;
