autocommit off;
create class foo (
	num numeric(5,2), i integer, s short, 
	f float, r real, d double, m monetary,
	si set(int), ms multiset(numeric, string), sq sequence(float),
	dt date, t time, ut timestamp, vb bit varying(4), b bit(11));
	
insert into foo values(123.45, 345, 127, 23.456e0, 123.45e0, 1.2234342e0,
		       12.56, set{1,2,3,4}, multiset{1.234, 'test1', 23.45},
		       sequence{1.234e0, 23.45e0}, date '05/17/1963', 
		       time '12:33 PM', timestamp '02/14/1994 12:30pm', 
		       b'1010', b'1100110011');
		       
select * from foo;
select cast(345 as bit varying(123)) from class db_user;
select cast(i as bit varying(123)) from foo;
select cast(345 as bit(123)) from class db_user;
select cast(i as bit(123)) from foo;
select cast(345 as date) from class db_user;
select cast(i as date) from foo;
select cast(345 as time) from class db_user;
select cast(i as time) from foo;
select cast(345 as timestamp) from class db_user;
select cast(i as timestamp) from foo;
select cast(345 as set(int)) from class db_user;
select cast(i as set(int)) from foo;
select cast(345 as multiset(int)) from class db_user;
select cast(i as multiset(int)) from foo;
select cast(345 as sequence(int)) from class db_user;
select cast(i as sequence(int)) from foo;
select cast(s as bit varying(123)) from foo;
select cast(s as bit(123)) from foo;
select cast(s as date) from foo;
select cast(s as time) from foo;
select cast(s as timestamp) from foo;
select cast(s as set(int)) from foo;
select cast(s as multiset(int)) from foo;
select cast(s as sequence(int)) from foo;
select cast(12.345 as bit varying(123)) from class db_user;
select cast(num as bit varying(123)) from foo;
select cast(12.345 as bit(123)) from class db_user;
select cast(num as bit(123)) from foo;
select cast(12.345 as date) from class db_user;
select cast(num as date) from foo;
select cast(12.345 as time) from class db_user;
select cast(num as time) from foo;
select cast(12.345 as timestamp) from class db_user;
select cast(num as timestamp) from foo;
select cast(12.345 as set(int)) from class db_user;
select cast(num as set(int)) from foo;
select cast(12.345 as multiset(int)) from class db_user;
select cast(num as multiset(int)) from foo;
select cast(12.345 as sequence(int)) from class db_user;
select cast(num as sequence(int)) from foo;
select cast(12.345e0 as bit varying(123)) from class db_user;
select cast(f as bit varying(123)) from foo;
select cast(12.345e0 as bit(123)) from class db_user;
select cast(f as bit(123)) from foo;
select cast(12.345e0 as date) from class db_user;
select cast(f as date) from foo;
select cast(12.345e0 as time) from class db_user;
select cast(f as time) from foo;
select cast(12.345e0 as timestamp) from class db_user;
select cast(f as timestamp) from foo;
select cast(12.345e0 as set(int)) from class db_user;
select cast(f as set(int)) from foo;
select cast(12.345e0 as multiset(int)) from class db_user;
select cast(f as multiset(int)) from foo;
select cast(12.345e0 as sequence(int)) from class db_user;
select cast(f as sequence(int)) from foo;
select cast(r as bit varying(123)) from foo;
select cast(r as bit(123)) from foo;
select cast(r as date) from foo;
select cast(r as time) from foo;
select cast(r as timestamp) from foo;
select cast(r as set(int)) from foo;
select cast(r as multiset(int)) from foo;
select cast(r as sequence(int)) from foo;
select cast(d as bit varying(123)) from foo;
select cast(d as bit(123)) from foo;
select cast(d as date) from foo;
select cast(d as time) from foo;
select cast(d as timestamp) from foo;
select cast(d as set(int)) from foo;
select cast(d as multiset(int)) from foo;
select cast(d as sequence(int)) from foo;
select cast(123.45 as bit varying(123)) from class db_user;
select cast(m as bit varying(123)) from foo;
select cast(123.45 as bit(123)) from class db_user;
select cast(m as bit(123)) from foo;
select cast(123.45 as date) from class db_user;
select cast(m as date) from foo;
select cast(123.45 as time) from class db_user;
select cast(m as time) from foo;
select cast(123.45 as timestamp) from class db_user;
select cast(m as timestamp) from foo;
select cast(123.45 as set(int)) from class db_user;
select cast(m as set(int)) from foo;
select cast(123.45 as multiset(int)) from class db_user;
select cast(m as multiset(int)) from foo;
select cast(123.45 as sequence(int)) from class db_user;
select cast(m as sequence(int)) from foo;
select cast(b'10101' as numeric(5,2)) from class db_user;
select cast(b as numeric(5,2)) from foo;
select cast(b'10101' as int) from class db_user;
select cast(b as int) from foo;
select cast(b'10101' as short) from class db_user;
select cast(b as short) from foo;
select cast(b'10101' as numeric(5,2)) from class db_user;
select cast(b as numeric(5,2)) from foo;
select cast(b'10101' as float) from class db_user;
select cast(b as float) from foo;
select cast(b'10101' as double) from class db_user;
select cast(b as double) from foo;
select cast(b'10101' as monetary) from class db_user;
select cast(b as monetary) from foo;
select cast(b'10101' as date) from class db_user;
select cast(b as date) from foo;
select cast(b'10101' as time) from class db_user;
select cast(b as time) from foo;
select cast(b'10101' as timestamp) from class db_user;
select cast(b as timestamp) from foo;
select cast(b'10101' as set(bit)) from class db_user;
select cast(b as set(bit)) from foo;
select cast(b'10101' as multiset(bit)) from class db_user;
select cast(b as multiset(bit)) from foo;
select cast(b'10101' as sequence(bit)) from class db_user;
select cast(b as sequence(bit)) from foo;
select cast(vb as numeric(5,2)) from foo;
select cast(vb as int) from foo;
select cast(vb as short) from foo;
select cast(vb as numeric(5,2)) from foo;
select cast(vb as float) from foo;
select cast(vb as double) from foo;
select cast(vb as monetary) from foo;
select cast(vb as date) from foo;
select cast(vb as time) from foo;
select cast(vb as timestamp) from foo;
select cast(vb as set(bit)) from foo;
select cast(vb as multiset(bit)) from foo;
select cast(vb as sequence(bit)) from foo;
select cast(date '10/09/1994' as int) from class db_user;
select cast(dt as int) from foo;
select cast(date '10/09/1994' as short) from class db_user;
select cast(dt as short) from foo;
select cast(date '10/09/1994' as numeric(5,2)) from class db_user;
select cast(dt as numeric(5,2)) from foo;
select cast(date '10/09/1994' as float) from class db_user;
select cast(dt as float) from foo;
select cast(date '10/09/1994' as double) from class db_user;
select cast(dt as double) from foo;
select cast(date '10/09/1994' as monetary) from class db_user;
select cast(dt as monetary) from foo;
select cast(date '10/09/1994' as bit) from class db_user;
select cast(dt as bit) from foo;
select cast(date '10/09/1994' as bit varying(12)) from class db_user;
select cast(dt as bit varying(12)) from foo;
select cast(date '10/09/1994' as time) from class db_user;
select cast(dt as time) from foo;
select cast(date '10/09/1994' as set(date)) from class db_user;
select cast(dt as set(date)) from foo;
select cast(date '10/09/1994' as multiset(date)) from class db_user;
select cast(dt as multiset(date)) from foo;
select cast(date '10/09/1994' as sequence(date)) from class db_user;
select cast(dt as sequence(date)) from foo;
select cast(time '12:33 PM' as int) from class db_user;
select cast(t as int) from foo;
select cast(time '12:33 PM' as short) from class db_user;
select cast(t as short) from foo;
select cast(time '12:33 PM' as numeric(5,2)) from class db_user;
select cast(t as numeric(5,2)) from foo;
select cast(time '12:33 PM' as float) from class db_user;
select cast(t as float) from foo;
select cast(time '12:33 PM' as double) from class db_user;
select cast(t as double) from foo;
select cast(time '12:33 PM' as monetary) from class db_user;
select cast(t as monetary) from foo;
select cast(time '12:33 PM' as bit) from class db_user;
select cast(t as bit) from foo;
select cast(time '12:33 PM' as bit varying(12)) from class db_user;
select cast(t as bit varying(12)) from foo;
select cast(time '12:33 PM' as date) from class db_user;
select cast(t as date) from foo;
select cast(time '12:33 PM' as set(date)) from class db_user;
select cast(t as set(date)) from foo;
select cast(time '12:33 PM' as multiset(date)) from class db_user;
select cast(t as multiset(date)) from foo;
select cast(time '12:33 PM' as sequence(date)) from class db_user;
select cast(t as sequence(date)) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as int) from class db_user;
select cast(t as int) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as short) from class db_user;
select cast(t as short) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as numeric(5,2)) 
from class db_user;
select cast(t as numeric(5,2)) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as float) from class db_user;
select cast(t as float) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as double) from class db_user;
select cast(t as double) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as monetary) from class db_user;
select cast(t as monetary) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as bit) from class db_user;
select cast(t as bit) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as bit varying(12)) 
from class db_user;
select cast(t as bit varying(12)) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as set(date)) from class db_user;
select cast(t as set(date)) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as multiset(date)) 
from class db_user;
select cast(t as multiset(date)) from foo;
select cast(timestamp '01/14/1994 12:34 PM' as sequence(date)) 
from class db_user;
select cast(t as sequence(date)) from foo;
select cast(set{1,2} as integer) from class db_user;
select cast(si as integer) from foo;
select cast(set{1,2} as short) from class db_user;
select cast(si as short) from foo;
select cast(set{1.2,2.1} as numeric(5,2)) from class db_user;
select cast(si as numeric(5,2)) from foo;
select cast(set{1.2e0,2.1e0} as float) from class db_user;
select cast(si as float) from foo;
select cast(set{1.2e0,2} as double) from class db_user;
select cast(si as double) from foo;
select cast(set{1,2} as monetary) from class db_user;
select cast(si as monetary) from foo;
select cast(set{1,2} as bit) from class db_user;
select cast(si as bit) from foo;
select cast(set{1,2} as bit varying(40)) from class db_user;
select cast(si as bit varying(40)) from foo;
select cast(set{1,2} as date) from class db_user;
select cast(si as date) from foo;
select cast(set{1,2} as time) from class db_user;
select cast(si as time) from foo;
select cast(set{1,2} as timestamp) from class db_user;
select cast(si as timestamp) from foo;
select cast(set{1,2} as sequence(int)) from class db_user;
select cast(si as sequence(int)) from foo;
select cast(multiset{1,2} as integer) from class db_user;
select cast(ms as integer) from foo;
select cast(multiset{1,2} as short) from class db_user;
select cast(ms as short) from foo;
select cast(multiset{1.2,2.1} as numeric(5,2)) from class db_user;
select cast(ms as numeric(5,2)) from foo;
select cast(multiset{1.2e0,2.1e0} as float) from class db_user;
select cast(ms as float) from foo;
select cast(multiset{1.2e0,2} as double) from class db_user;
select cast(ms as double) from foo;
select cast(multiset{1,2} as monetary) from class db_user;
select cast(ms as monetary) from foo;
select cast(multiset{1,2} as bit) from class db_user;
select cast(ms as bit) from foo;
select cast(multiset{1,2} as bit varying(40)) from class db_user;
select cast(ms as bit varying(40)) from foo;
select cast(multiset{1,2} as date) from class db_user;
select cast(ms as date) from foo;
select cast(multiset{1,2} as time) from class db_user;
select cast(ms as time) from foo;
select cast(multiset{1,2} as timestamp) from class db_user;
select cast(ms as timestamp) from foo;
select cast(multiset{1,2} as sequence(int)) from class db_user;
select cast(ms as sequence(int)) from foo;
select cast(sequence{1,2} as integer) from class db_user;
select cast(sq as integer) from foo;
select cast(sequence{1,2} as short) from class db_user;
select cast(sq as short) from foo;
select cast(sequence{1.2,2.1} as numeric(5,2)) from class db_user;
select cast(sq as numeric(5,2)) from foo;
select cast(sequence{1.2e0,2.1e0} as float) from class db_user;
select cast(sq as float) from foo;
select cast(sequence{1.2e0,2} as double) from class db_user;
select cast(sq as double) from foo;
select cast(sequence{1,2} as monetary) from class db_user;
select cast(sq as monetary) from foo;
select cast(sequence{1,2} as bit) from class db_user;
select cast(sq as bit) from foo;
select cast(sequence{1,2} as bit varying(40)) from class db_user;
select cast(sq as bit varying(40)) from foo;
select cast(sequence{1,2} as date) from class db_user;
select cast(sq as date) from foo;
select cast(sequence{1,2} as time) from class db_user;
select cast(sq as time) from foo;
select cast(sequence{1,2} as timestamp) from class db_user;
select cast(sq as timestamp) from foo;
select cast(sequence{1,2} as set(int)) from class db_user;
select cast(sq as multiset(int)) from foo;
select cast(sequence{1,2} as multiset(int)) from class db_user;
select cast(sq as set(int)) from foo;
rollback;
