autocommit off;
(select descr from joe.product_c) union (select price from joe.product_v);
(select descr from joe.product_c) intersection (select price from joe.product_v);
(select descr from joe.product_c) difference (select price from joe.product_v);
(select price, descr from joe.product_c) union (select price from joe.product_v);
(select price, descr from joe.product_c) intersection (select price from joe.product_v);
(select price, descr from joe.product_c) difference (select price from joe.product_v);
(select price, descr from joe.product_c) union (select descr, price from joe.product_v);
(select price, descr from joe.product_c) intersection (select descr, price from joe.product_v);
(select price, descr from joe.product_c) difference (select descr, price from joe.product_v);
rollback;
