-- Verification for CBRD-25842, CBRD-26443: partition-key function crash
-- 
-- Description:
-- When the following functions are used in a partition key expression, a segmentation fault occurs when inserting into the table:

-- SYS_DATE, SYSDATE
-- SYS_TIME, SYSTIME
-- SYS_DATETIME, SYSDATETIME
-- SYS_TIMESTAMP, SYSTIMESTAMP
-- CURRENT_DATE, CURDATE
-- CURRENT_TIME, CURTIME
-- CURRENT_TIMESTAMP, LOCALTIME, LOCALTIMESTAMP
-- CURRENT_DATETIME, NOW
-- UTC_TIME, UTC_DATE
-- UTC_TIMESTAMP
-- TZ_OFFSET
-- RAND
-- RANDOM
-- This test verifies that the above functions cannot be used in partition key expressions.

drop table if exists SYS_DATE_TBL;
drop table if exists SYS_TIME_TBL;
drop table if exists SYS_DATETIME_TBL;
drop table if exists SYS_TIMESTAMP_TBL;
drop table if exists CURRENT_DATE_TBL;
drop table if exists CURRENT_TIME_TBL;
drop table if exists CURRENT_TIMESTAMP_TBL;
drop table if exists CURRENT_DATETIME_TBL;
drop table if exists UTC_TIME_TBL;
drop table if exists UTC_DATE_TBL;
drop table if exists UTC_TIMESTAMP_TBL;
drop table if exists TZ_OFFSET_TBL;
drop table if exists RAND_TBL;

evaluate 'Case 1: CREATE TABLE with SYS_DATE function';
CREATE TABLE SYS_DATE_TBL (col1 int) PARTITION BY HASH (SYS_DATE + col1) PARTITIONS 10;

CREATE TABLE SYS_DATE_TBL (col1 int) PARTITION BY HASH (SYSDATE + col1) PARTITIONS 10;

evaluate 'Case 2: CREATE TABLE with SYS_TIME function';
CREATE TABLE SYS_TIME_TBL (col1 int) PARTITION BY HASH (SYS_TIME + col1) PARTITIONS 10;

CREATE TABLE SYS_TIME_TBL (col1 int) PARTITION BY HASH (SYSTIME + col1) PARTITIONS 10;

evaluate 'Case 3: CREATE TABLE with SYS_DATETIME function';
CREATE TABLE SYS_DATETIME_TBL (col1 int) PARTITION BY HASH (SYS_DATETIME + col1) PARTITIONS 10;

CREATE TABLE SYS_DATETIME_TBL (col1 int) PARTITION BY HASH (SYSDATETIME + col1) PARTITIONS 10;

evaluate 'Case 4: CREATE TABLE with SYS_TIMESTAMP function';
CREATE TABLE SYS_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (SYS_TIMESTAMP + col1) PARTITIONS 10;

CREATE TABLE SYS_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (SYSTIMESTAMP + col1) PARTITIONS 10;

evaluate 'Case 5: CREATE TABLE with CURRENT_DATE function';
CREATE TABLE CURRENT_DATE_TBL (col1 int) PARTITION BY HASH (CURDATE() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_DATE_TBL (col1 int) PARTITION BY HASH (CURRENT_DATE() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_DATE_TBL (col1 int) PARTITION BY HASH (CURRENT_DATE + col1) PARTITIONS 10;

evaluate 'Case 6: CREATE TABLE with CURRENT_TIME function';
CREATE TABLE CURRENT_TIME_TBL (col1 int) PARTITION BY HASH (CURTIME() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIME_TBL (col1 int) PARTITION BY HASH (CURRENT_TIME() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIME_TBL (col1 int) PARTITION BY HASH (CURRENT_TIME + col1) PARTITIONS 10;

evaluate 'Case 7: CREATE TABLE with CURRENT_TIMESTAMP function';
CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (CURRENT_TIMESTAMP + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (CURRENT_TIMESTAMP() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (LOCALTIME + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (LOCALTIME() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (LOCALTIMESTAMP + col1) PARTITIONS 10;

CREATE TABLE CURRENT_TIMESTAMP_TBL (col1 int) PARTITION BY HASH (LOCALTIMESTAMP() + col1) PARTITIONS 10;

evaluate 'Case 8: CREATE TABLE with CURRENT_DATETIME function';
CREATE TABLE CURRENT_DATETIME_TBL(col1 int) PARTITION BY HASH(CURRENT_DATETIME + col1) PARTITIONS 10;

CREATE TABLE CURRENT_DATETIME_TBL(col1 int) PARTITION BY HASH(CURRENT_DATETIME() + col1) PARTITIONS 10;

CREATE TABLE CURRENT_DATETIME_TBL(col1 int) PARTITION BY HASH(NOW() + col1) PARTITIONS 10;

evaluate 'Case 9: CREATE TABLE with UTC_TIME function';
CREATE TABLE UTC_TIME_TBL(col1 int) PARTITION BY HASH(UTC_TIME() + col1) PARTITIONS 10;

evaluate 'Case 10: CREATE TABLE with UTC_DATE function';
CREATE TABLE UTC_DATE_TBL(col1 int) PARTITION BY HASH(UTC_DATE() + col1) PARTITIONS 10;

evaluate 'Case 11: CREATE TABLE with UTC_TIMESTAMP function';
CREATE TABLE UTC_TIMESTAMP_TBL(col1 int) PARTITION BY HASH(UTC_TIMESTAMP() + col1) PARTITIONS 10;

evaluate 'Case 12: CREATE TABLE with TZ_OFFSET function';
CREATE TABLE TZ_OFFSET_TBL(col1 int) PARTITION BY HASH(TZ_OFFSET(col1)) PARTITIONS 10;

evaluate 'Case 13: CREATE TABLE with RAND function';
CREATE TABLE RAND_TBL(col1 int) PARTITION BY HASH(RAND() + col1) PARTITIONS 10;

CREATE TABLE RAND_TBL(col1 int) PARTITION BY HASH(RANDOM() + col1) PARTITIONS 10;

drop table if exists SYS_DATE_TBL;
drop table if exists SYS_TIME_TBL;
drop table if exists SYS_DATETIME_TBL;
drop table if exists SYS_TIMESTAMP_TBL;
drop table if exists CURRENT_DATE_TBL;
drop table if exists CURRENT_TIME_TBL;
drop table if exists CURRENT_TIMESTAMP_TBL;
drop table if exists CURRENT_DATETIME_TBL;
drop table if exists UTC_TIME_TBL;
drop table if exists UTC_DATE_TBL;
drop table if exists UTC_TIMESTAMP_TBL;
drop table if exists TZ_OFFSET_TBL;
drop table if exists RAND_TBL;
