CREATE TABLE blogtopic (topicId INTEGER, postDate DATE, closedDate DATE);
insert into blogtopic value(1,DATE '2010-01-01',DATE '2010-01-02');
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE closedDate IS NULL;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE closedDate IS NOT NULL;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId in (1,2,3,4);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId not in (1,2,3,4);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId is any (select topicId from blogtopic);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId>any (select topicId from blogtopic);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId>some (select topicId from blogtopic);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE not(select topicId from blogtopic)<>0;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId !=1;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId =1;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId <=1;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId >=1;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId <1;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId >1;
drop index my_filter_index ON blogtopic (topicId);

CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId between 2 and 9;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE EXISTS(select * from my_filter_index);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE not EXISTS(select * from my_filter_index);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId > (select count(*) from my_filter_index);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE topicId-5/6 > (select count(*) from my_filter_index);
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE postDate >SYS_DATE;
drop index my_filter_index ON blogtopic (topicId);
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE abs(topicId)>5;
drop index my_filter_index ON blogtopic (topicId);
drop table blogtopic;

CREATE TABLE blogtopic (topicId INTEGER, postDate DATE, closedDate char(10));
CREATE INDEX my_filter_index ON blogtopic (topicId) WHERE closedDate like '%AB%';
drop index my_filter_index ON blogtopic (topicId);
drop table blogtopic;
