autocommit off;

CREATE TABLE tbl1 (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY);
CREATE TABLE tbl2 (id INT AUTO_INCREMENT(100,1), last_id INT);
CREATE TRIGGER t1 AFTER INSERT ON tbl1 EXECUTE INSERT INTO tbl2 VALUES(NULL, LAST_INSERT_ID());
INSERT INTO tbl1 VALUES(NULL);

SELECT LAST_INSERT_ID();
SELECT * FROM tbl1;

INSERT INTO tbl1 VALUES(NULL), (NULL), (NULL);
SELECT LAST_INSERT_ID();
SELECT * FROM tbl1 ORDER BY 1;

drop trigger t1;
drop table tbl1, tbl2;

commit;

CREATE TABLE tbl1 (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY);
CREATE TABLE tbl2 (id INT AUTO_INCREMENT(100,1), last_id INT);
CREATE TRIGGER t1 DEFERRED INSERT ON tbl1 EXECUTE INSERT INTO tbl2 VALUES(NULL, LAST_INSERT_ID());
INSERT INTO tbl1 VALUES(NULL);
SELECT LAST_INSERT_ID();

EXECUTE DEFERRED TRIGGER t1;
SELECT LAST_INSERT_ID();
SELECT * FROM tbl1;

drop trigger t1;
drop table tbl1, tbl2;

rollback;

autocommit on;

