drop table if exists x,y,z;
create table x(a int,b int,c int,d int,e int); 
insert into x values(1,1,1,1,1);
create table y(i int);
create table z(i int);
insert into y values(1);
insert into y values(2);
insert into z values(3);
insert into z values(4);
insert into z values(5);
select a,b,c from x where a in (with cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where a not in (with cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where exists (with cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where not exists (with cte as (select i from y union select i from z)select * from cte);
drop table if exists x,y,z;
create table x(a int,b int,c int,d int,e int); 
insert into x values(1,1,1,1,1);
create table y(i int);
create table z(i int);
insert into y values(1);
insert into y values(2);
insert into z values(3);
insert into z values(4);
insert into z values(5);
select a,b,c from x where a in (with recursive cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where a not in (with recursive cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where exists (with recursive cte as (select i from y union select i from z)select * from cte);
select a,b,c from x where not exists (with recursive cte as (select i from y union select i from z)select * from cte);
drop table if exists x,y,z;
create table x(a int,b int,c int,d int,e int);
insert into x values(1,1,1,1,1);
insert into x values(2,2,2,2,2);
create table y(i int);
create table z(i int);
insert into y values(1);
insert into y values(2);
insert into z values(1);
insert into z values(2);
insert into z values(3);
select a,b,c from x where a in (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte) order by 1;
select a,b,c from x where a not in (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte) order by 1;
select a,b,c from x where exists (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte) order by 1;
select a,b,c from x where not exists  (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte) order by 1;
drop table if exists x,y,z;
create table x(a int,b int,c int,d int,e int);
insert into x values(1,1,1,1,1);
insert into x values(2,2,2,2,2);
create table y(i int);
create table z(i int);
insert into y values(1);
insert into z values(1);
insert into z values(2);
insert into z values(3);
select a,b,c from x where a in (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte);
select a,b,c from x where a not in (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte);
select a,b,c from x where exists (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte);
select a,b,c from x where not exists (with recursive cte as (select y.i from y,z where y.i=z.i)select * from cte);
drop table if exists x,y,z;
